Simopticon: ParameterDefinition Class Reference
ParameterDefinition Class Reference
parameters
A class storing information on the properties of parameters that are being optimized.
#include "ParameterDefinition.h"
Public Member Functions
ParameterDefinition (coordinate min, coordinate max, std::string config="", std::string unit="")
Creates a ParameterDefinition with the given minimum, maximum, configuration string and unit.
coordinate getMin () const
Returns the minimum value of the Parameter stored in min.
coordinate getMax () const
Returns the maximum value of the Parameter stored in max.
const std::string & getUnit () const
Returns the unit string of the Parameter stored in unit.
const std::string & getConfig () const
Returns the configuration string of the Parameter stored in config.
Private Attributes
const coordinate min
Minimum value of the Parameter.
const coordinate max
Maximum value of the Parameter.
const std::string unit
Unit of the Parameter (optional).
const std::string config
String containing configuration details of the Parameter (optional).
Detailed Description
A class storing information on the properties of parameters that are being optimized.
Definition at line 17 of file ParameterDefinition.h.
Constructor & Destructor Documentation
ParameterDefinition()
ParameterDefinition::ParameterDefinition (coordinate min, coordinate max, std::string config = "", std::string unit = "")
Creates a ParameterDefinition with the given minimum, maximum, configuration string and unit.
Parameters
min Minimum value of the Parameter.
max Maximum value of the Parameter.
config Configuration string for the Parameter (optional).
unit Unit of the Parameter (optional)
Definition at line 11 of file ParameterDefinition.cpp.
References config, max, min, and unit.
Member Function Documentation
getConfig()
const std::string & ParameterDefinition::getConfig () const
Returns the configuration string of the Parameter stored in config.
Returns
A string reference containing the configuration.
Definition at line 35 of file ParameterDefinition.cpp.
References config.
Referenced by Parameter::getConfig().
getMax()
coordinate ParameterDefinition::getMax () const
Returns the maximum value of the Parameter stored in max.
Returns
A coordinate representing the maximum value.
Definition at line 27 of file ParameterDefinition.cpp.
References max.
Referenced by ParameterNormalizer::denormalize(), and Parameter::getMax().
getMin()
coordinate ParameterDefinition::getMin () const
Returns the minimum value of the Parameter stored in min.
Returns
A coordinate representing the minimum value.
Definition at line 23 of file ParameterDefinition.cpp.
References min.
Referenced by ParameterNormalizer::denormalize(), and Parameter::getMin().
getUnit()
const std::string & ParameterDefinition::getUnit () const
Returns the unit string of the Parameter stored in unit.
Returns
A string reference containing the unit.
Definition at line 31 of file ParameterDefinition.cpp.
References unit.
Referenced by Parameter::getUnit().
Member Data Documentation
config
const std::string ParameterDefinition::config private
String containing configuration details of the Parameter (optional).
May be used to transfer configuration information for SimulationRunner.
Definition at line 35 of file ParameterDefinition.h.
Referenced by ParameterDefinition(), and getConfig().
max
const coordinate ParameterDefinition::max private
Maximum value of the Parameter.
Definition at line 26 of file ParameterDefinition.h.
Referenced by ParameterDefinition(), and getMax().
min
const coordinate ParameterDefinition::min private
Minimum value of the Parameter.
Definition at line 22 of file ParameterDefinition.h.
Referenced by ParameterDefinition(), and getMin().
unit
const std::string ParameterDefinition::unit private
Unit of the Parameter (optional).
Definition at line 30 of file ParameterDefinition.h.
Referenced by ParameterDefinition(), and getUnit().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/parameters/ParameterDefinition.h
/home/runner/work/simopticon/simopticon/src/parameters/ParameterDefinition.cpp