Simopticon: RandomNeighbors Class Reference
RandomNeighbors Class Reference
optimizer » randomneighbors
A class capable of finding the minimum of a blackbox function using the Random Neighbors algorithm.
#include "RandomNeighbors.h"
Public Member Functions
RandomNeighbors (Controller &ctrl, const std::list< std::shared_ptr< ParameterDefinition >> &params, nlohmann::json config)
Creates a RandomNeighbors optimizer that evaluates functions with the given Controller, optimizes the given ParameterDefinition list and stops as defined by the given StoppingCondition.
void runOptimization () override
Starts the optimization.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Optimizer
Optimizer (Controller &ctrl, std::list< std::shared_ptr< ParameterDefinition >> params)
Creates an Optimizer which can request values from the given Controller and tries to optimize the given parameters.
ValueMap & getValueMap () const
Returns a reference to Controller::valueMap.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Abortable
virtual void abort ()
Sets aborted to true.
Private Member Functions
void saveProgress (functionValue bestVal, size_t evaluations) const
Prints the current number of iterations, evaluations, rectangles and the current optimal value to a .csv file.
Private Attributes
size_t iterations = 1
Number of iterations completed.
const size_t parallelTrials
Number of (typically parallel executed) parameter combinations per iteration.
const double neighborhoodWidth
The search width around the current optimum relative to each parameter bounds pair.
const double localSearchProbability
The probability for searching in the neighborhood instead of globally.
bool lastLocal = false
True, if the last iteration was a local search, false if global search.
StoppingCondition stopCon
An object deciding when the optimization stops.
bool trackProgress
Defines if the current number of iterations, evaluations, rectangles and the optimal value should be recorded into a .csv file after each iteration.
std::string lastEvaluations
A string for logging purposes containing the evaluation of the simulation runs of the last iteration.
Additional Inherited Members
Protected Member Functions inherited from Optimizer
std::map< parameterCombination, functionValue > requestValues (const std::list< parameterCombination > &params)
Requests the values when using certain parameterCombinations from controller.
Protected Attributes inherited from Optimizer
std::list< std::shared_ptr< ParameterDefinition > > parameters
List of parameters to be optimized.
Protected Attributes inherited from Abortable
bool aborted = false
Defines if the process has been aborted, i.e.
Static Protected Attributes inherited from Status
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class capable of finding the minimum of a blackbox function using the Random Neighbors algorithm.
Author
Burkhard Hensel
Definition at line 37 of file RandomNeighbors.h.
Constructor & Destructor Documentation
RandomNeighbors()
RandomNeighbors::RandomNeighbors (Controller & ctrl, const std::list< std::shared_ptr< ParameterDefinition >> & params, nlohmann::json config)
Creates a RandomNeighbors optimizer that evaluates functions with the given Controller, optimizes the given ParameterDefinition list and stops as defined by the given StoppingCondition.
Parameters
ctrl Controller to be used for evaluating the optimized function.
params ParameterDefinition list to be optimized.
config Configuration parameters as JSON.
Definition at line 15 of file RandomNeighbors.cpp.
References RandomNeighbors().
Referenced by RandomNeighbors().
Member Function Documentation
getName()
std::string RandomNeighbors::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 105 of file RandomNeighbors.cpp.
getStatus()
std::string RandomNeighbors::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 109 of file RandomNeighbors.cpp.
References iterations, lastEvaluations, and lastLocal.
getStatusBar()
std::string RandomNeighbors::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 126 of file RandomNeighbors.cpp.
runOptimization()
void RandomNeighbors::runOptimization () override virtual
Starts the optimization.
Only returns when an iteration has completed and stopCon deems the optimization complete or when abort was called in the last iteration.
Implements Optimizer.
Definition at line 26 of file RandomNeighbors.cpp.
References Optimizer::getValueMap(), iterations, lastEvaluations, lastLocal, localSearchProbability, parallelTrials, saveProgress(), and trackProgress.
saveProgress()
void RandomNeighbors::saveProgress (functionValue bestVal, size_t evaluations) const private
Prints the current number of iterations, evaluations, rectangles and the current optimal value to a .csv file.
Parameters
bestVal Value at the current minimum.
evaluations Number of evaluations conducted by the optimization.
Definition at line 93 of file RandomNeighbors.cpp.
Referenced by runOptimization().
Member Data Documentation
iterations
size_t RandomNeighbors::iterations = 1 private
Number of iterations completed.
Definition at line 42 of file RandomNeighbors.h.
Referenced by getStatus(), and runOptimization().
lastEvaluations
std::string RandomNeighbors::lastEvaluations private
A string for logging purposes containing the evaluation of the simulation runs of the last iteration.
Definition at line 71 of file RandomNeighbors.h.
Referenced by getStatus(), and runOptimization().
lastLocal
bool RandomNeighbors::lastLocal = false private
True, if the last iteration was a local search, false if global search.
Definition at line 58 of file RandomNeighbors.h.
Referenced by getStatus(), and runOptimization().
localSearchProbability
const double RandomNeighbors::localSearchProbability private
The probability for searching in the neighborhood instead of globally.
Definition at line 54 of file RandomNeighbors.h.
Referenced by runOptimization().
neighborhoodWidth
const double RandomNeighbors::neighborhoodWidth private
The search width around the current optimum relative to each parameter bounds pair.
Definition at line 50 of file RandomNeighbors.h.
parallelTrials
const size_t RandomNeighbors::parallelTrials private
Number of (typically parallel executed) parameter combinations per iteration.
Definition at line 46 of file RandomNeighbors.h.
Referenced by runOptimization().
stopCon
StoppingCondition RandomNeighbors::stopCon private
An object deciding when the optimization stops.
Definition at line 62 of file RandomNeighbors.h.
trackProgress
bool RandomNeighbors::trackProgress private
Defines if the current number of iterations, evaluations, rectangles and the optimal value should be recorded into a .csv file after each iteration.
Can be set in config.
Definition at line 67 of file RandomNeighbors.h.
Referenced by runOptimization().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/optimizer/randomneighbors/RandomNeighbors.h
/home/runner/work/Simopticon/Simopticon/src/optimizer/randomneighbors/RandomNeighbors.cpp