Simopticon: Controller Class Reference
Controller Class Reference
controller
A class responsible for communication between Optimizer, SimulationRunner and Evaluation and also user interaction such as tracking results, updating StatusBar and handling interrupts by the user via Abortable.
#include "Controller.h"
Classes
struct stepstate
A struct keeping track of the currently running optimization step for StatusBar::updateStatus.
Public Member Functions
Controller (const std::filesystem::path &configPath, bool isStub=false)
Creates a Controller which uses Optimizer, SimulationRunner and Evaluation as specified in the given config files.
void run ()
Starts optimization process by calling Optimizer::runOptimization.
std::map< parameterCombination, functionValue > requestValues (const std::list< parameterCombination > &params)
Searches valueMap for results to given parameterCombinations.
ValueMap & getValueMap ()
Returns valueMap.
void abort () override
Aborts optimizer using Optimizer::abort.
Protected Attributes
StatusBar statusBar
StatusBar object used for output.
std::unique_ptr< Optimizer > optimizer
Optimizer defining an optimization strategy.
std::unique_ptr< SimulationRunner > runner
SimulationRunner able to run simulations with certain parameterCombinations.
std::unique_ptr< Evaluation > evaluation
Evaluation capable of evaluating data produced by runner.
std::unique_ptr< ValueMap > valueMap
ValueMap containing all values gathered by simulating and evaluating certain parameterCombinations.
struct Controller::stepstate stepState
An object keeping track of the current optimization step.
Protected Attributes inherited from Abortable
bool aborted = false
Defines if the process has been aborted, i.e.
Private Member Functions
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > &runs)
Calls the runner to run simulations for the given parameterCombinations.
virtual std::map< parameterCombination, functionValue, CmpVectorSharedParameter > evaluate (const std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId >>, CmpVectorSharedParameter > &simulationResults)
Calls the evaluation to evaluate the given result files.
virtual void removeOldResultfiles ()
Removes all result files that don't belong to the best n results, where n is configured in main config.
void saveValues ()
Prints all evaluated parameterCombinations and their respective values to results/values.csv.
virtual void updateStatus ()
Updates the statusBar using StatusBar::updateStatus.
Private Attributes
bool keepFiles
Defines if result files of best simulations are kept after optimization.
bool printValues
Defines if all found values should be recorded in a .csv file after optimization has finished.
std::map< parameterCombination, std::filesystem::path > topResults
Saves the best n parameterCombinations and the corresponding path to the result files, if keepFiles is true.
std::chrono::milliseconds statusInterval = std::chrono::milliseconds(0)
Interval of updates of StatusBar using updateStatus in concurrent status thread.
Detailed Description
A class responsible for communication between Optimizer, SimulationRunner and Evaluation and also user interaction such as tracking results, updating StatusBar and handling interrupts by the user via Abortable.
Author
Per Natzschka
Definition at line 44 of file Controller.h.
Constructor & Destructor Documentation
Controller()
Controller::Controller (const std::filesystem::path & configPath, bool isStub = false) explicit
Creates a Controller which uses Optimizer, SimulationRunner and Evaluation as specified in the given config files.
If called by the constructor of StubController, runner and evaluation get assigned null-pointers.
Parameters
configPath Path to the main config. Chosen by first command line argument.
isStub Defines whether the constructor was called by constructor of StubController.
Definition at line 40 of file Controller.cpp.
References statusInterval, and valueMap.
Referenced by StubController::StubController().
Member Function Documentation
abort()
void Controller::abort () override virtual
Aborts optimizer using Optimizer::abort.
Aborts the concurrent thread that regularly updates statusBar.
Reimplemented from Abortable.
Definition at line 275 of file Controller.cpp.
References Abortable::abort(), and optimizer.
evaluate()
std::map< parameterCombination, functionValue, CmpVectorSharedParameter > Controller::evaluate (const std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId >>, CmpVectorSharedParameter > & simulationResults) private virtual
Calls the evaluation to evaluate the given result files.
Updates statusBar before and after execution of evaluation.
Parameters
simulationResults A map which maps the parameterCombinations that must be evaluated to their respective file paths of simulation results and runIds.
Returns
A map which maps the given parameterCombinations to their respective functionValue.
Reimplemented in StubController.
Definition at line 208 of file Controller.cpp.
References updateStatus().
getValueMap()
ValueMap & Controller::getValueMap ()
Returns valueMap.
Returns
A ValueMap object.
Definition at line 173 of file Controller.cpp.
References valueMap.
Referenced by Optimizer::getValueMap().
removeOldResultfiles()
void Controller::removeOldResultfiles () private virtual
Removes all result files that don't belong to the best n results, where n is configured in main config.
If keepFiles is false, all result files are removed.
Reimplemented in StubController.
Definition at line 224 of file Controller.cpp.
References ValueMap::getTopVals(), keepFiles, topResults, and valueMap.
Referenced by requestValues().
requestValues()
std::map< parameterCombination, functionValue > Controller::requestValues (const std::list< parameterCombination > & params)
Searches valueMap for results to given parameterCombinations.
Each combination that hasn't been simulated is simulated and evaluated using runSimulations and evaluate. Updates statusBar before and after execution.
Parameters
params A set of parameterCombinations to be evaluated.
Returns
A map which maps the given parameterCombinations to their respective functionValue.
Definition at line 139 of file Controller.cpp.
References Controller::stepstate::next(), removeOldResultfiles(), and updateStatus().
Referenced by Optimizer::requestValues().
run()
void Controller::run ()
Starts optimization process by calling Optimizer::runOptimization.
Creates concurrent thread that updates statusBar every statusInterval milliseconds. Prints results in command line after optimization is done using StatusBar::printResults.
Definition at line 177 of file Controller.cpp.
References Controller::stepstate::next(), optimizer, printValues, Optimizer::runOptimization(), saveValues(), statusInterval, and updateStatus().
runSimulations()
std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > Controller::runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > & runs) private virtual
Calls the runner to run simulations for the given parameterCombinations.
Updates statusBar before and after execution of simulations.
Parameters
runs A set of parameterCombinations to be executed.
Returns
A map which maps the given parameterCombinations to their respective result file paths and runIds.
Reimplemented in StubController.
Definition at line 201 of file Controller.cpp.
References updateStatus().
saveValues()
void Controller::saveValues () private
Prints all evaluated parameterCombinations and their respective values to results/values.csv.
Definition at line 242 of file Controller.cpp.
Referenced by run().
updateStatus()
void Controller::updateStatus () private virtual
Updates the statusBar using StatusBar::updateStatus.
Reimplemented in StubController.
Definition at line 267 of file Controller.cpp.
References evaluation, Controller::stepstate::get(), ValueMap::getSize(), ValueMap::getTopVals(), optimizer, runner, statusBar, Controller::stepstate::stepChanged, StatusBar::updateStatus(), and valueMap.
Referenced by evaluate(), requestValues(), run(), and runSimulations().
Member Data Documentation
evaluation
std::unique_ptr<Evaluation> Controller::evaluation protected
Evaluation capable of evaluating data produced by runner.
Definition at line 114 of file Controller.h.
Referenced by updateStatus().
keepFiles
bool Controller::keepFiles private
Defines if result files of best simulations are kept after optimization.
Can be set in main config.
Definition at line 49 of file Controller.h.
Referenced by removeOldResultfiles().
optimizer
std::unique_ptr<Optimizer> Controller::optimizer protected
Optimizer defining an optimization strategy.
Definition at line 106 of file Controller.h.
Referenced by abort(), run(), updateStatus(), and StubController::updateStatus().
printValues
bool Controller::printValues private
Defines if all found values should be recorded in a .csv file after optimization has finished.
Can be set in main config.
Definition at line 54 of file Controller.h.
Referenced by run().
runner
std::unique_ptr<SimulationRunner> Controller::runner protected
SimulationRunner able to run simulations with certain parameterCombinations.
Definition at line 110 of file Controller.h.
Referenced by updateStatus().
statusBar
StatusBar Controller::statusBar protected
StatusBar object used for output.
Definition at line 102 of file Controller.h.
Referenced by updateStatus(), and StubController::updateStatus().
statusInterval
std::chrono::milliseconds Controller::statusInterval = std::chrono::milliseconds(0) private
Interval of updates of StatusBar using updateStatus in concurrent status thread.
Definition at line 62 of file Controller.h.
Referenced by Controller(), and run().
topResults
std::map<parameterCombination, std::filesystem::path> Controller::topResults private
Saves the best n parameterCombinations and the corresponding path to the result files, if keepFiles is true.
n can be set in main config.
Definition at line 58 of file Controller.h.
Referenced by removeOldResultfiles().
valueMap
std::unique_ptr<ValueMap> Controller::valueMap protected
ValueMap containing all values gathered by simulating and evaluating certain parameterCombinations.
Definition at line 118 of file Controller.h.
Referenced by Controller(), getValueMap(), removeOldResultfiles(), updateStatus(), and StubController::updateStatus().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/controller/Controller.h
/home/runner/work/Simopticon/Simopticon/src/controller/Controller.cpp