Simopticon: ChildRect Class Reference
ChildRect Class Reference
Optimizer » Direct » Hyrect
A class representing a HyRect that has a parent HyRect.
#include "ChildRect.h"
Public Member Functions
ChildRect (position pos, shared_ptr< HyRect > parent)
Creates a ChildRect with the given relative position and parent rectangle.
array< vector< dirCoordinate >, 2 > getSamplingVertices () override
Returns the coordinates of two opposite corner points of the rectangle.
bool operator== (const HyRect &rect) const override
Checks if the current and the given HyRect objects are equal by comparing their pos, D, and t.
Public Member Functions inherited from HyRect
HyRect (dimension D, position pos, depth t)
Creates a HyRect with the given dimensionality, position and depth.
dirCoordinate getDiagonalLength () const
Returns the length of the diagonal of the rectangle.
depth getDepth () const
Returns the value of t.
position getPos () const
Returns the value of pos.
dimension getSplitDim () const
Calculates the dimension where this rectangle must be or has been split by divide.
functionValue getAvgValue () const
Returns the value of avgValue.
dimension getD () const
Returns the value of D.
void setAvgValue (functionValue value)
Sets the value of avgValue.
bool operator< (const HyRect &rect) const
Compares depth t and avgValue of the given HyRect objects.
bool operator!= (const HyRect &rhs) const
Checks if the current and the given HyRect objects are unequal by comparing their pos, D, and t.
bool operator> (const HyRect &rhs) const
Compares depth t and avgValue of the given HyRect objects.
bool operator<= (const HyRect &rhs) const
Compares depth t and avgValue of the given HyRect objects.
bool operator>= (const HyRect &rhs) const
Compares depth t and avgValue of the given HyRect objects.
Private Attributes
shared_ptr< HyRect > parent
Reference to the parent rectangle.
Additional Inherited Members
Static Public Member Functions inherited from HyRect
static array< shared_ptr< HyRect >, 3 > divide (const shared_ptr< HyRect > &ptr)
Divides the given rectangle into three smaller ChildRect which take the given HyRect as a parent.
Protected Attributes inherited from HyRect
dimension D
Dimensionality of the rectangle.
depth t
Depth of the rectangle in the partition tree.
position pos
Position of the rectangle relative to its parent rectangle.
functionValue avgValue = INFINITY
Mean between the values obtained at the parameters returned by getSamplingVertices.
Detailed Description
A class representing a HyRect that has a parent HyRect.
Used for all HyRect where depth .
Definition at line 12 of file ChildRect.h.
Constructor & Destructor Documentation
ChildRect()
ChildRect::ChildRect (position pos, shared_ptr< HyRect > parent)
Creates a ChildRect with the given relative position and parent rectangle.
Parameters
pos Relative position to the given parent rectangle.
parent Parent rectangle in the partition tree.
Definition at line 5 of file ChildRect.cpp.
References HyRect::HyRect(), HyRect::getD(), HyRect::getDepth(), and parent.
Referenced by HyRect::divide().
Member Function Documentation
getSamplingVertices()
array< vector< dirCoordinate >, 2 > ChildRect::getSamplingVertices () override virtual
Returns the coordinates of two opposite corner points of the rectangle.
The returned vertices must be sampled. The vertices are calculated recursively based on the sampling vertices of parent.
Returns
An array containing two dirCoordinate vectors of the sampled vertices.
Implements HyRect.
Definition at line 9 of file ChildRect.cpp.
References HyRect::getSamplingVertices(), HyRect::getSplitDim(), parent, and HyRect::pos.
operator==()
bool ChildRect::operator== (const HyRect & rect) const override virtual
Checks if the current and the given HyRect objects are equal by comparing their pos, D, and t.
Parameters
rect HyRect to be compared.
Returns
A boolean defining if the HyRect objects have the same position in the partition tree.
Reimplemented from HyRect.
Definition at line 27 of file ChildRect.cpp.
References HyRect::getPos(), parent, and HyRect::pos.
Member Data Documentation
parent
shared_ptr<HyRect> ChildRect::parent private
Reference to the parent rectangle.
Used for recursive calculation of getSamplingVertices.
Definition at line 17 of file ChildRect.h.
Referenced by ChildRect(), getSamplingVertices(), and operator==().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/optimizer/direct/hyrect/ChildRect.h
/home/runner/work/simopticon/simopticon/src/optimizer/direct/hyrect/ChildRect.cpp