Simopticon: Status Class Reference
Status Class Reference
status
An interface defining functions for status updates on configuration and progress of a class.
#include "Status.h"
Public Member Functions
virtual std::string getName ()
Returns a string representing the name of the implementing component in natural language.
virtual std::string getStatus ()
Returns a string representing the current state of the implementing component.
virtual std::string getStatusBar ()
Returns a string representing the current progress of the calculations of the implementing component.
Static Protected Attributes
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
An interface defining functions for status updates on configuration and progress of a class.
Used for creation of a StatusBar. Overriding the defined methods is not mandatory but recommended.
Definition at line 26 of file Status.h.
Member Function Documentation
getName()
std::string Status::getName () virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented in SimulationRunner, PlexeSimulationRunner, Optimizer, DirectOptimizer, Evaluation, and ConstantHeadway.
Definition at line 21 of file Status.cpp.
References NO_NAME.
Referenced by Evaluation::getName(), Optimizer::getName(), SimulationRunner::getName(), and StatusBar::printStatus().
getStatus()
std::string Status::getStatus () virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented in SimulationRunner, PlexeSimulationRunner, Optimizer, DirectOptimizer, Evaluation, and ConstantHeadway.
Definition at line 13 of file Status.cpp.
References NO_STATUS_SUPPORT.
Referenced by Evaluation::getStatus(), Optimizer::getStatus(), SimulationRunner::getStatus(), and StatusBar::printStatus().
getStatusBar()
std::string Status::getStatusBar () virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented in SimulationRunner, PlexeSimulationRunner, Optimizer, DirectOptimizer, Evaluation, and ConstantHeadway.
Definition at line 17 of file Status.cpp.
References NO_STATUS_SUPPORT.
Referenced by Evaluation::getStatusBar(), Optimizer::getStatusBar(), SimulationRunner::getStatusBar(), and StatusBar::updateStatus().
Member Data Documentation
NO_NAME
const std::string Status::NO_NAME = "No name specified" static protected
Default message returned by getName if the implementing class does not override the function.
Definition at line 35 of file Status.h.
Referenced by getName().
NO_STATUS_SUPPORT
const std::string Status::NO_STATUS_SUPPORT = "Component doesn't support status updates!" static protected
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
Definition at line 31 of file Status.h.
Referenced by getStatus(), and getStatusBar().
The documentation for this class was generated from the following files:
src/status/Status.h
src/status/Status.cpp