Simopticon: Evaluation Class Reference
Evaluation Class Reference abstract
evaluation
A class capable of evaluating simulation results and scoring them with a value which is treated as the function value for the optimization.
#include "Evaluation.h"
Public Member Functions
virtual functionValue processOutput (std::filesystem::path path, std::set< runId > experimentIds)=0
Returns a value to the results of a single simulation run.
virtual std::map< std::pair< std::filesystem::path, std::set< runId > >, functionValue > processOutput (const std::set< std::pair< std::filesystem::path, std::set< runId >>> &experimentResults)
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Additional Inherited Members
Static Protected Attributes inherited from Status
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class capable of evaluating simulation results and scoring them with a value which is treated as the function value for the optimization.
A lower value is considered better in this framework. The optimized function can be viewed as an error function.
Definition at line 32 of file Evaluation.h.
Member Function Documentation
getName()
std::string Evaluation::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 17 of file Evaluation.cpp.
References Status::getName().
getStatus()
std::string Evaluation::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 21 of file Evaluation.cpp.
References Status::getStatus().
getStatusBar()
std::string Evaluation::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 25 of file Evaluation.cpp.
References Status::getStatusBar().
processOutput() [1/2]
std::map< std::pair< std::filesystem::path, std::set< runId > >, functionValue > Evaluation::processOutput (const std::set< std::pair< std::filesystem::path, std::set< runId >>> & experimentResults) virtual
   Returns values to the results of multiple simulation runs.
fi * Simply calls processOutput(std::filesystem::path, std::set<runId>) multiple times if not overridden.
Parameters
experimentResults Paths to and identifiers of the simulation results.
Returns
A map which maps the given results to their respective performance value.
Reimplemented in ConstantHeadway.
Definition at line 9 of file Evaluation.cpp.
References processOutput().
processOutput() [2/2]
virtual functionValue Evaluation::processOutput (std::filesystem::path path, std::set< runId > experimentIds) pure virtual
Returns a value to the results of a single simulation run.
Parameters
path Path to the result files.
experimentIds Identifiers of certain simulation runs within the directory represented by the given path.
Returns
A value that represents the performance of the simulation - the lower the better.
Implemented in ConstantHeadway.
Referenced by processOutput().
The documentation for this class was generated from the following files:
src/evaluation/Evaluation.h
src/evaluation/Evaluation.cpp