Simopticon: Multithreaded< Key, T, Compare, Allocator > Class Template Reference
Multithreaded< Key, T, Compare, Allocator > Class Template Reference abstract
utils
A class implementing concurrent execution of the same function for different arguments.
#include "Multithreaded.h"
Public Member Functions
Multithreaded (unsigned int threads)
Creates a Multithreaded class that does not use more than the given number of threads.
Protected Member Functions
virtual std::map< Key, T, Compare, Allocator > runMultithreadedFunctions (std::set< Key, Compare > runs)
Pushes given tasks into queue, creates concurrent threads and merges them when execution is done.
virtual std::map< Key, T, Compare, Allocator > multithreadFunction ()
Function that is executed by each thread.
Protected Attributes
const unsigned int NR_THREADS
Maximum number of concurrent threads to be used in ThreadPool.
ThreadsafeQueue< Key > queue
ThreadsafeQueue containing the arguments that have to be processed by the ThreadPool.
Private Member Functions
virtual T work (Key arg)=0
Function that should be executed concurrently on different arguments.
Detailed Description
template<class Key, class T, class Compare = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>>
class Multithreaded< Key, T, Compare, Allocator >
A class implementing concurrent execution of the same function for different arguments.
The function must be implemented through work and execution follows the ThreadPool design pattern.
Template Parameters
Key Argument type of the concurrent work function.
T Result type of the concurrent work function.
Compare Comparison for objects of type Key.
Allocator Allocator for pairs of constant Key and T.
Author
Per Natzschka
Definition at line 27 of file Multithreaded.h.
Constructor & Destructor Documentation
Multithreaded()
template<class Key , class T , class Compare , class Allocator > Multithreaded< Key, T, Compare, Allocator >::Multithreaded (unsigned int threads) explicit
Creates a Multithreaded class that does not use more than the given number of threads.
Parameters
threads Maximum number of threads to use.
Definition at line 12 of file Multithreaded.tpp.
References Multithreaded< Key, T, Compare, Allocator >::NR_THREADS.
Referenced by SimulationRunner::SimulationRunner().
Member Function Documentation
multithreadFunction()
template<class Key , class T , class Compare , class Allocator > std::map< Key, T, Compare, Allocator > Multithreaded< Key, T, Compare, Allocator >::multithreadFunction protected virtual
Function that is executed by each thread.
As long as queue is not empty, tasks are started. When queue is empty, the processed results are returned
Returns
A map which maps arguments to their respective calculated values.
Definition at line 36 of file Multithreaded.tpp.
References Multithreaded< Key, T, Compare, Allocator >::queue, and Multithreaded< Key, T, Compare, Allocator >::work().
Referenced by Multithreaded< Key, T, Compare, Allocator >::runMultithreadedFunctions().
runMultithreadedFunctions()
template<class Key , class T , class Compare , class Allocator > std::map< Key, T, Compare, Allocator > Multithreaded< Key, T, Compare, Allocator >::runMultithreadedFunctions (std::set< Key, Compare > runs) protected virtual
Pushes given tasks into queue, creates concurrent threads and merges them when execution is done.
Parameters
runs Set of arguments on which work should to be executed.
Returns
A map which maps arguments to their respective calculated values.
Definition at line 17 of file Multithreaded.tpp.
References Multithreaded< Key, T, Compare, Allocator >::multithreadFunction(), Multithreaded< Key, T, Compare, Allocator >::NR_THREADS, and Multithreaded< Key, T, Compare, Allocator >::queue.
Referenced by SimulationRunner::runSimulations().
work()
template<class Key , class T , class Compare = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> virtual T Multithreaded< Key, T, Compare, Allocator >::work (Key arg) private pure virtual
Function that should be executed concurrently on different arguments.
Parameters
arg Argument of the concurrently executed function.
Returns
Return value of the concurrently executed function.
Implemented in SimulationRunner, and PlexeSimulationRunner.
Referenced by Multithreaded< Key, T, Compare, Allocator >::multithreadFunction().
Member Data Documentation
NR_THREADS
template<class Key , class T , class Compare = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const unsigned int Multithreaded< Key, T, Compare, Allocator >::NR_THREADS protected
Maximum number of concurrent threads to be used in ThreadPool.
Definition at line 40 of file Multithreaded.h.
Referenced by Multithreaded< Key, T, Compare, Allocator >::Multithreaded(), and Multithreaded< Key, T, Compare, Allocator >::runMultithreadedFunctions().
queue
template<class Key , class T , class Compare = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> ThreadsafeQueue<Key> Multithreaded< Key, T, Compare, Allocator >::queue protected
ThreadsafeQueue containing the arguments that have to be processed by the ThreadPool.
Definition at line 44 of file Multithreaded.h.
Referenced by Multithreaded< Key, T, Compare, Allocator >::multithreadFunction(), and Multithreaded< Key, T, Compare, Allocator >::runMultithreadedFunctions().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/utils/Multithreaded.h
/home/runner/work/Simopticon/Simopticon/src/utils/Multithreaded.tpp