Simopticon: StatusBar Class Reference
StatusBar Class Reference
status
A class used to conduct command line output containing information about the state of the used Optimizer, SimulationRunner and Evaluation along with the found optima.
#include "StatusBar.h"
Public Member Functions
void updateStatus (Status *opt, Status *runner, Status *eval, const std::pair< parameterCombination, functionValue > &currentVal, bool stepChanged=false, step currentStep=INIT)
Updates the output in the command line with gathered information from the used Optimizer, SimulationRunner and Evaluation.
Static Public Member Functions
static void printResults (std::list< std::pair< parameterCombination, std::pair< functionValue, std::filesystem::path >>> top)
Prints the given parameterCombinations and respective values to command line.
Static Private Member Functions
static void printResult (const parameterCombination &cords, functionValue optimum)
Prints the given result command line.
static void printStatus (Status *object)
Prints the Status of the given object to the command line using Status::getStatus.
Private Attributes
std::pair< parameterCombination, functionValue > lastVal
Pair of parameterCombination and respective value used to discern if the best value has changed since the last call to updateStatus.
step lastStep = INIT
Step which the optimization was in when updateStatus was called the last time.
std::string lastStatus
Last values of the StatusBar output (excluding value returned by Status::getStatusBar)
Static Private Attributes
static const std::string LARGE_DIVIDER = "\n\n" + std::string(70, '#') + "\n"
Large divider used to visibly divide two sections of content.
static const std::string SMALL_DIVIDER = std::string(70, '-') + "\n"
Small divider used to visibly divide two sections of content.
Detailed Description
A class used to conduct command line output containing information about the state of the used Optimizer, SimulationRunner and Evaluation along with the found optima.
Definition at line 38 of file StatusBar.h.
Member Function Documentation
printResult()
void StatusBar::printResult (const parameterCombination & cords, functionValue optimum) static private
Prints the given result command line.
Parameters
cords parameterCombination of the given result.
optimum Value of the given result.
Definition at line 56 of file StatusBar.cpp.
References Parameter::getConfig(), Parameter::getUnit(), and Parameter::getVal().
Referenced by printResults(), and updateStatus().
printResults()
void StatusBar::printResults (std::list< std::pair< parameterCombination, std::pair< functionValue, std::filesystem::path >>> top) static
Prints the given parameterCombinations and respective values to command line.
Parameters
top List of parameterCombinations and respective values to be printed.
Definition at line 75 of file StatusBar.cpp.
References LARGE_DIVIDER, printResult(), and SMALL_DIVIDER.
printStatus()
void StatusBar::printStatus (Status * object) static private
Prints the Status of the given object to the command line using Status::getStatus.
Parameters
object Object that inherits from Status and whose state is being printed.
Definition at line 70 of file StatusBar.cpp.
References Status::getName(), and Status::getStatus().
Referenced by updateStatus().
updateStatus()
void StatusBar::updateStatus (Status * opt, Status * runner, Status * eval, const std::pair< parameterCombination, functionValue > & currentVal, bool stepChanged = false, step currentStep = INIT)
Updates the output in the command line with gathered information from the used Optimizer, SimulationRunner and Evaluation.
If the current optimum or the step the optimization is in has changed since the last call, the whole output is printed again. Otherwise only the progress of the active component obtained by Status::getStatusBar is updated.
Parameters
opt Pointer to Optimizer used in optimization.
runner Pointer to SimulationRunner used in optimization.
eval Pointer to Evaluation used in optimization.
currentVal parameterCombination and respective value of the current optimum.
stepChanged Boolean defining whether the current step has changed since the last call.
currentStep Current step the optimization is in.
Definition at line 17 of file StatusBar.cpp.
References Status::getStatusBar(), LARGE_DIVIDER, lastStatus, lastStep, lastVal, printResult(), printStatus(), and SMALL_DIVIDER.
Referenced by Controller::updateStatus(), and StubController::updateStatus().
Member Data Documentation
LARGE_DIVIDER
const std::string StatusBar::LARGE_DIVIDER = "\n\n" + std::string(70, '#') + "\n" static private
Large divider used to visibly divide two sections of content.
Definition at line 43 of file StatusBar.h.
Referenced by printResults(), and updateStatus().
lastStatus
std::string StatusBar::lastStatus private
Last values of the StatusBar output (excluding value returned by Status::getStatusBar)
Definition at line 60 of file StatusBar.h.
Referenced by updateStatus().
lastStep
step StatusBar::lastStep = INIT private
Step which the optimization was in when updateStatus was called the last time.
Definition at line 56 of file StatusBar.h.
Referenced by updateStatus().
lastVal
std::pair<parameterCombination, functionValue> StatusBar::lastVal private
Pair of parameterCombination and respective value used to discern if the best value has changed since the last call to updateStatus.
Definition at line 52 of file StatusBar.h.
Referenced by updateStatus().
SMALL_DIVIDER
const std::string StatusBar::SMALL_DIVIDER = std::string(70, '-') + "\n" static private
Small divider used to visibly divide two sections of content.
Definition at line 47 of file StatusBar.h.
Referenced by printResults(), and updateStatus().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/status/StatusBar.h
/home/runner/work/Simopticon/Simopticon/src/status/StatusBar.cpp