Simopticon: Optimizer Class Reference
Optimizer Class Reference abstract
optimizer
A class containing an optimization strategy which searches the minimum of a blackbox function given through argument-value pairs.
#include "Optimizer.h"
Public Member Functions
Optimizer (Controller &ctrl, list< shared_ptr< ParameterDefinition >> params)
Creates an Optimizer which can request values from the given Controller and tries to optimize the given parameters.
virtual void runOptimization ()=0
Starts the optimization process.
ValueMap & getValueMap () const
Returns a reference to Controller::valueMap.
string getName () override
Returns a string representing the name of the implementing component in natural language.
string getStatus () override
Returns a string representing the current state of the implementing component.
string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Abortable
virtual void abort ()
Sets aborted to true.
Protected Member Functions
map< vector< shared_ptr< Parameter > >, functionValue > requestValues (const list< vector< shared_ptr< Parameter >>> &params)
Requests the values when using certain Parameter combinations from controller.
Protected Attributes
list< shared_ptr< ParameterDefinition > > parameters
List of parameters to be optimized.
Protected Attributes inherited from Abortable
bool aborted = false
Defines if the process has been aborted, i.e.
Private Attributes
Controller & controller
Reference to the executing Controller to be able to request values using Controller::requestValues.
Additional Inherited Members
Static Protected Attributes inherited from Status
static const string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class containing an optimization strategy which searches the minimum of a blackbox function given through argument-value pairs.
The Optimizer has control over which Parameter combinations are simulated and evaluated as well as the duration of the optimization. If abort is called the optimization strategy should finish the optimization as soon as possible.
Definition at line 44 of file Optimizer.h.
Constructor & Destructor Documentation
Optimizer()
Optimizer::Optimizer (Controller & ctrl, list< shared_ptr< ParameterDefinition >> params)
Creates an Optimizer which can request values from the given Controller and tries to optimize the given parameters.
Parameters
ctrl Controller to be used for evaluation of Parameter combinations.
params List of ParameterDefinition defining the parameters that must be optimized.
Definition at line 17 of file Optimizer.cpp.
References controller, and parameters.
Member Function Documentation
getName()
string Optimizer::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 25 of file Optimizer.cpp.
References Status::getName().
getStatus()
string Optimizer::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 29 of file Optimizer.cpp.
References Status::getStatus().
getStatusBar()
string Optimizer::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 33 of file Optimizer.cpp.
References Status::getStatusBar().
getValueMap()
ValueMap & Optimizer::getValueMap () const
Returns a reference to Controller::valueMap.
Basically calls Controller::getValueMap on controller.
Returns
Definition at line 21 of file Optimizer.cpp.
References controller, and Controller::getValueMap().
Referenced by DirectOptimizer::runOptimization().
requestValues()
map< vector< shared_ptr< Parameter > >, functionValue > Optimizer::requestValues (const list< vector< shared_ptr< Parameter >>> & params) protected
Requests the values when using certain Parameter combinations from controller.
Basically calls Controller::requestValues with the given values.
Parameters
params Parameter combinations to be evaluated.
Returns
A map which maps Parameter combinations to their respective values.
Definition at line 13 of file Optimizer.cpp.
References controller, and Controller::requestValues().
runOptimization()
virtual void Optimizer::runOptimization () pure virtual
Starts the optimization process.
Should only return if the optimization strategy deems the optimization complete or when abort is called.
Implemented in DirectOptimizer.
Referenced by Controller::run().
Member Data Documentation
controller
Controller& Optimizer::controller private
Reference to the executing Controller to be able to request values using Controller::requestValues.
Definition at line 49 of file Optimizer.h.
Referenced by Optimizer(), getValueMap(), and requestValues().
parameters
list<shared_ptr<ParameterDefinition> > Optimizer::parameters protected
List of parameters to be optimized.
Definition at line 55 of file Optimizer.h.
Referenced by Optimizer().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/optimizer/Optimizer.h
/home/runner/work/simopticon/simopticon/src/optimizer/Optimizer.cpp