Simopticon: ParameterNormalizer Class Reference
ParameterNormalizer Class Reference
optimizer » direct
A class used for transforming parameters between the actual Parameter space and the unit hypercube used in DIRECT algorithm.
#include "ParameterNormalizer.h"
Public Member Functions
ParameterNormalizer (std::list< std::shared_ptr< ParameterDefinition >> parameters)
Creates a ParameterNormalizer with the given optimized parameters.
parameterCombination denormalize (std::vector< dirCoordinate > cords)
Transforms the given point in the unit hypercube into a parameterCombination.
Static Public Member Functions
static std::vector< dirCoordinate > normalize (const parameterCombination &params)
Transforms the given parameterCombination into a point in the unit hypercube.
Private Attributes
std::list< std::shared_ptr< ParameterDefinition > > parameters
ParameterDefinition of the optimized parameters.
Detailed Description
A class used for transforming parameters between the actual Parameter space and the unit hypercube used in DIRECT algorithm.
Definition at line 24 of file ParameterNormalizer.h.
Constructor & Destructor Documentation
ParameterNormalizer()
ParameterNormalizer::ParameterNormalizer (std::list< std::shared_ptr< ParameterDefinition >> parameters) explicit
Creates a ParameterNormalizer with the given optimized parameters.
Parameters
parameters ParameterDefinition of the optimized parameters.
Definition at line 13 of file ParameterNormalizer.cpp.
References parameters.
Member Function Documentation
denormalize()
parameterCombination ParameterNormalizer::denormalize (std::vector< dirCoordinate > cords)
Transforms the given point in the unit hypercube into a parameterCombination.
Parameters
cords Point in the unit hypercube to be transformed.
Returns
A parameterCombination corresponding to the given point in the unit hypercube.
Definition at line 25 of file ParameterNormalizer.cpp.
References ContinuousParameter::ContinuousParameter(), ParameterDefinition::getMax(), ParameterDefinition::getMin(), and parameters.
normalize()
std::vector< dirCoordinate > ParameterNormalizer::normalize (const parameterCombination & params) static
Transforms the given parameterCombination into a point in the unit hypercube.
Parameters
params parameterCombination to be transformed.
Returns
A point in the unit hypercube corresponding to the given parameterCombination.
Definition at line 17 of file ParameterNormalizer.cpp.
References Parameter::getMax(), Parameter::getMin(), and Parameter::getVal().
Member Data Documentation
parameters
std::list<std::shared_ptr<ParameterDefinition> > ParameterNormalizer::parameters private
ParameterDefinition of the optimized parameters.
Definition at line 29 of file ParameterNormalizer.h.
Referenced by ParameterNormalizer(), and denormalize().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/optimizer/direct/ParameterNormalizer.h
/home/runner/work/Simopticon/Simopticon/src/optimizer/direct/ParameterNormalizer.cpp