Simopticon: HyRect Class Reference
HyRect Class Reference abstract
Optimizer » Direct » Hyrect
An abstract class representing a rectangular part of the search space.
#include "HyRect.h"
Public Member Functions
HyRect (dimension D, position pos, depth t)
Creates a HyRect with the given dimensionality, position and depth.
virtual array< vector< dirCoordinate >, 2 > getSamplingVertices ()=0
Returns the coordinates of two opposite corner points of the rectangle.
dirCoordinate getDiagonalLength () const
Returns the length of the diagonal of the rectangle.
depth getDepth () const
Returns the value of t.
position getPos () const
Returns the value of pos.
dimension getSplitDim () const
Calculates the dimension where this rectangle must be or has been split by divide.
functionValue getAvgValue () const
Returns the value of avgValue.
dimension getD () const
Returns the value of D.
void setAvgValue (functionValue value)
Sets the value of avgValue.
virtual bool operator== (const HyRect &rect) const
Checks if the current and the given HyRect objects are equal by comparing their pos, D, and t.
bool operator< (const HyRect &rect) const
Compares depth t and avgValue of the given HyRect objects.
bool operator!= (const HyRect &rhs) const
Checks if the current and the given HyRect objects are unequal by comparing their pos, D, and t.
bool operator> (const HyRect &rhs) const
Compares depth t and avgValue of the given HyRect objects.
bool operator<= (const HyRect &rhs) const
Compares depth t and avgValue of the given HyRect objects.
bool operator>= (const HyRect &rhs) const
Compares depth t and avgValue of the given HyRect objects.
Static Public Member Functions
static array< shared_ptr< HyRect >, 3 > divide (const shared_ptr< HyRect > &ptr)
Divides the given rectangle into three smaller ChildRect which take the given HyRect as a parent.
Protected Attributes
dimension D
Dimensionality of the rectangle.
depth t
Depth of the rectangle in the partition tree.
position pos
Position of the rectangle relative to its parent rectangle.
functionValue avgValue = INFINITY
Mean between the values obtained at the parameters returned by getSamplingVertices.
Detailed Description
An abstract class representing a rectangular part of the search space.
Definition at line 35 of file HyRect.h.
Constructor & Destructor Documentation
HyRect()
HyRect::HyRect (dimension D, position pos, depth t)
Creates a HyRect with the given dimensionality, position and depth.
Parameters
D Dimensionality of the rectangle (i.e. the search space).
pos Position relative to parent rectangle.
t Depth of the rectangle in partition tree.
Definition at line 6 of file HyRect.cpp.
References D, pos, and t.
Referenced by BaseRect::BaseRect(), and ChildRect::ChildRect().
Member Function Documentation
divide()
array< shared_ptr< HyRect >, 3 > HyRect::divide (const shared_ptr< HyRect > & ptr) static
Divides the given rectangle into three smaller ChildRect which take the given HyRect as a parent.
Parameters
ptr Reference to a shared_ptr to the HyRect that is being divided.
Returns
An array of ChildRect instances generated by dividing the given HyRect.
Definition at line 9 of file HyRect.cpp.
References ChildRect::ChildRect().
getAvgValue()
functionValue HyRect::getAvgValue () const
Returns the value of avgValue.
Returns
A functionValue representing the average value on the sampled corners of the rectangle.
Definition at line 35 of file HyRect.cpp.
References avgValue.
Referenced by DirectOptimizer::estimatedValue(), CmpSharedHyrect::operator()(), and GrahamScan::scan().
getD()
dimension HyRect::getD () const
Returns the value of D.
Returns
A dimension representing the number of dimensions of the rectangle.
Definition at line 67 of file HyRect.cpp.
References D.
Referenced by ChildRect::ChildRect().
getDepth()
depth HyRect::getDepth () const
Returns the value of t.
Returns
A depth value representing the depth of the rectangle in the partition tree.
Definition at line 31 of file HyRect.cpp.
References t.
Referenced by ChildRect::ChildRect(), and GrahamScan::scan().
getDiagonalLength()
dirCoordinate HyRect::getDiagonalLength () const
Returns the length of the diagonal of the rectangle.
Basically calculates the euclidian distance between the vertices returned by getSamplingVertices. Instead of actually invoking the costly recursive getSamplingVertices function, a calculation based on t is executed
Returns
A dirCoordinate representing the diagonal length of the rectangle.
Definition at line 16 of file HyRect.cpp.
References D, and t.
Referenced by DirectOptimizer::estimatedValue(), and GrahamScan::scan().
getPos()
position HyRect::getPos () const
Returns the value of pos.
Returns
A position value representing the relative position to the parent rectangle.
Definition at line 27 of file HyRect.cpp.
References pos.
Referenced by ChildRect::operator==().
getSamplingVertices()
virtual array<vector<dirCoordinate>, 2> HyRect::getSamplingVertices () pure virtual
Returns the coordinates of two opposite corner points of the rectangle.
The returned vertices must be sampled.
Returns
An array containing two dirCoordinate vectors of the sampled vertices.
Implemented in ChildRect, and BaseRect.
Referenced by ChildRect::getSamplingVertices(), and CmpSharedHyrect::operator()().
getSplitDim()
dimension HyRect::getSplitDim () const
Calculates the dimension where this rectangle must be or has been split by divide.
Since the split dimensions are simply chosen in ascending order the calculations only needs the depth stored in t.
Returns
A dimension where the HyRect has been oder will be split.
Definition at line 23 of file HyRect.cpp.
References D, and t.
Referenced by ChildRect::getSamplingVertices().
operator!=()
bool HyRect::operator!= (const HyRect & rhs) const
Checks if the current and the given HyRect objects are unequal by comparing their pos, D, and t.
Basically negates operator==.
Parameters
rhs HyRect to be compared.
Returns
A boolean defining if the HyRect objects have different positions in the partition tree.
Definition at line 51 of file HyRect.cpp.
References operator==().
operator<()
bool HyRect::operator< (const HyRect & rect) const
Compares depth t and avgValue of the given HyRect objects.
Parameters
rect HyRect to be compared.
Returns
A boolean defining if the depth t of this HyRect is greater than that of the given HyRect or whether the avgValue is less than that of the given HyRect if depth t is the same.
Definition at line 47 of file HyRect.cpp.
References avgValue, and t.
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool HyRect::operator<= (const HyRect & rhs) const
Compares depth t and avgValue of the given HyRect objects.
Basically negates operator>.
Parameters
rhs HyRect to be compared.
Returns
A boolean defining if the depth t of this HyRect is greater than or equal to that of the given HyRect or whether the avgValue is less than or equal that of the given HyRect if depth t is the same.
Definition at line 59 of file HyRect.cpp.
References operator<().
operator==()
bool HyRect::operator== (const HyRect & rect) const virtual
Checks if the current and the given HyRect objects are equal by comparing their pos, D, and t.
Parameters
rect HyRect to be compared.
Returns
A boolean defining if the HyRect objects have the same position in the partition tree.
Reimplemented in ChildRect.
Definition at line 43 of file HyRect.cpp.
References D, pos, and t.
Referenced by operator!=().
operator>()
bool HyRect::operator> (const HyRect & rhs) const
Compares depth t and avgValue of the given HyRect objects.
Basically calls operator< on the switched inputs.
Parameters
rhs HyRect to be compared.
Returns
A boolean defining if the depth t of this HyRect is less or equal than that of the given HyRect or whether the avgValue is greater than or equal that of the given HyRect if depth t is the same.
Definition at line 55 of file HyRect.cpp.
References operator<().
operator>=()
bool HyRect::operator>= (const HyRect & rhs) const
Compares depth t and avgValue of the given HyRect objects.
Basically negates operator<.
Parameters
rhs HyRect to be compared.
Returns
A boolean defining if the depth t of this HyRect is less than or equal that of the given HyRect or whether the avgValue is greater than or equal that of the given HyRect if depth t is the same.
Definition at line 63 of file HyRect.cpp.
References operator<().
setAvgValue()
void HyRect::setAvgValue (functionValue value)
Sets the value of avgValue.
Parameters
value Average value sampled at the corners of the rectangle.
Definition at line 39 of file HyRect.cpp.
References avgValue.
Member Data Documentation
avgValue
functionValue HyRect::avgValue = INFINITY protected
Mean between the values obtained at the parameters returned by getSamplingVertices.
Definition at line 55 of file HyRect.h.
Referenced by getAvgValue(), operator<(), and setAvgValue().
D
dimension HyRect::D protected
Dimensionality of the rectangle.
Is equivalent to the dimensionality of the search space, i.e. the number of optimized parameters.
Definition at line 41 of file HyRect.h.
Referenced by HyRect(), getD(), getDiagonalLength(), BaseRect::getSamplingVertices(), getSplitDim(), and operator==().
pos
position HyRect::pos protected
Position of the rectangle relative to its parent rectangle.
For BaseRect, pos is always BASE.
Definition at line 51 of file HyRect.h.
Referenced by HyRect(), getPos(), ChildRect::getSamplingVertices(), operator==(), and ChildRect::operator==().
t
depth HyRect::t protected
Depth of the rectangle in the partition tree.
Equal to the number of transitive parent rectangles. For BaseRect, t is always 0.
Definition at line 46 of file HyRect.h.
Referenced by HyRect(), getDepth(), getDiagonalLength(), getSplitDim(), operator<(), and operator==().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/optimizer/direct/hyrect/HyRect.h
/home/runner/work/simopticon/simopticon/src/optimizer/direct/hyrect/HyRect.cpp