Simopticon: DirectOptimizer Class Reference
DirectOptimizer Class Reference
optimizer » direct
A class capable of finding the minimum of a blackbox function using the DIRECT algorithm.
#include "DirectOptimizer.h"
Public Member Functions
DirectOptimizer (Controller &ctrl, const std::list< std::shared_ptr< ParameterDefinition >> &params, StoppingCondition con, bool trackProgress, bool printValues)
Creates a DirectOptimizer that evaluates functions with the given Controller, optimizes the given ParameterDefinition list and stops as defined by the given StoppingCondition.
void runOptimization () override
Starts the optimization using the DIRECT algorithm.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
size_t getPartitionSize ()
Returns the number of rectangles stored in activeRects.
Public Member Functions inherited from Optimizer
Optimizer (Controller &ctrl, std::list< std::shared_ptr< ParameterDefinition >> params)
Creates an Optimizer which can request values from the given Controller and tries to optimize the given parameters.
ValueMap & getValueMap () const
Returns a reference to Controller::valueMap.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Abortable
virtual void abort ()
Sets aborted to true.
Private Member Functions
std::map< std::vector< dirCoordinate >, functionValue > getValues (const std::list< std::vector< dirCoordinate >> &points)
Returns the function values at the given points.
std::list< std::shared_ptr< HyRect > > optimalRectangles (size_t nrRects, functionValue phi)
Finds potentially optimal rectangles that should be divided in the current iteration.
void addActiveRects (const std::list< std::shared_ptr< HyRect >> &rects)
Requests values at the corners of the given rectangles and add all given HyRect instances to activeRects.
void removeActiveRects (const std::list< std::shared_ptr< HyRect >> &rects)
Removes the given rectangles from activeRects.
void saveProgress (functionValue bestVal, size_t evaluations, size_t nrRects) const
Prints the current number of iterations, evaluations, rectangles and the current optimal value to a .csv file.
void saveValues ()
Prints all evaluated parameterCombinations and their respective values to a .csv file.
Static Private Member Functions
static functionValue estimatedValue (const std::shared_ptr< HyRect > &rect, double k)
Calculates the minimum expected value in a rectangle when the given Lipschitz constant is assumed.
Private Attributes
const dimension D
Number of parameters to be optimized (meaning dimensions of the search space).
size_t iterations = 0
Number of iterations completed.
StoppingCondition stopCon
An object deciding when the optimization stops.
Levels level
An object used switching between different levels between global and local search.
ParameterNormalizer normalizer
An object used for transformation between the unit hypercube used in DIRECT and the actual parameter space.
bool trackProgress
Defines if the current number of iterations, evaluations, rectangles and the optimal value should be recorded into a .csv file after each iteration.
bool printValues
Defines if all found values should be recorded in a .csv file after optimization has finished.
std::map< depth, std::set< std::shared_ptr< HyRect >, CmpSharedHyrect >, std::greater<> > activeRects
Holds all rectangles that are immediate part of the current partition.
Additional Inherited Members
Protected Member Functions inherited from Optimizer
std::map< parameterCombination, functionValue > requestValues (const std::list< parameterCombination > &params)
Requests the values when using certain parameterCombinations from controller.
Protected Attributes inherited from Optimizer
std::list< std::shared_ptr< ParameterDefinition > > parameters
List of parameters to be optimized.
Protected Attributes inherited from Abortable
bool aborted = false
Defines if the process has been aborted, i.e.
Static Protected Attributes inherited from Status
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class capable of finding the minimum of a blackbox function using the DIRECT algorithm.
Definition at line 39 of file DirectOptimizer.h.
Constructor & Destructor Documentation
DirectOptimizer()
DirectOptimizer::DirectOptimizer (Controller & ctrl, const std::list< std::shared_ptr< ParameterDefinition >> & params, StoppingCondition con, bool trackProgress, bool printValues)
Creates a DirectOptimizer that evaluates functions with the given Controller, optimizes the given ParameterDefinition list and stops as defined by the given StoppingCondition.
Parameters
ctrl Controller to be used for evaluating the optimized function.
params ParameterDefinition list to be optimized.
con StoppingCondition defining the end of optimization.
trackProgress Defines whether the progress should be printed in a .csv file.
printValues Defines whether all obtained values should be printed in a .csv file after optimization.
Definition at line 16 of file DirectOptimizer.cpp.
References DirectOptimizer(), level, printValues, and trackProgress.
Referenced by DirectOptimizer().
Member Function Documentation
addActiveRects()
void DirectOptimizer::addActiveRects (const std::list< std::shared_ptr< HyRect >> & rects) private
Requests values at the corners of the given rectangles and add all given HyRect instances to activeRects.
Parameters
rects Rectangles to be evaluated and added.
Definition at line 113 of file DirectOptimizer.cpp.
estimatedValue()
functionValue DirectOptimizer::estimatedValue (const std::shared_ptr< HyRect > & rect, double k) static private
Calculates the minimum expected value in a rectangle when the given Lipschitz constant is assumed.
Parameters
rect Rectangle the minimum is searched for.
k Lipschitz constant that is assumed in this rectangle.
Returns
A value representing an estimation of the absolute minimum reachable in this rectangle.
Definition at line 93 of file DirectOptimizer.cpp.
References HyRect::getAvgValue(), and HyRect::getDiagonalLength().
getName()
std::string DirectOptimizer::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 196 of file DirectOptimizer.cpp.
getPartitionSize()
size_t DirectOptimizer::getPartitionSize ()
Returns the number of rectangles stored in activeRects.
Returns
A number representing the size of the partition.
Definition at line 213 of file DirectOptimizer.cpp.
Referenced by getStatus().
getStatus()
std::string DirectOptimizer::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 200 of file DirectOptimizer.cpp.
References Levels::getLevel(), getPartitionSize(), iterations, and level.
getStatusBar()
std::string DirectOptimizer::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 209 of file DirectOptimizer.cpp.
getValues()
std::map< std::vector< dirCoordinate >, functionValue > DirectOptimizer::getValues (const std::list< std::vector< dirCoordinate >> & points) private
Returns the function values at the given points.
Basically transforms the given points from dirCoordinates in the hypercube to actual coordinates in the parameter space using normalizer and calls requestValues.
Parameters
points List of points in the hypercube to be evaluated.
Returns
A map which maps the given points to their respective values.
Definition at line 75 of file DirectOptimizer.cpp.
optimalRectangles()
std::list< std::shared_ptr< HyRect > > DirectOptimizer::optimalRectangles (size_t nrRects, functionValue phi) private
Finds potentially optimal rectangles that should be divided in the current iteration.
First filters for only the best rectangles of a size from a subset of all activeRects determined by level. Then uses GrahamScan to filter after the first condition of the DIRECT algorithm. Finally filters for the second condition of the DIRECT algorithm.
Parameters
nrRects Size of the partition (meaning number of rectangles in activeRects).
phi Value at the current minimum.
Returns
A list of potentially optimal rectangles.
Definition at line 97 of file DirectOptimizer.cpp.
removeActiveRects()
void DirectOptimizer::removeActiveRects (const std::list< std::shared_ptr< HyRect >> & rects) private
Removes the given rectangles from activeRects.
Parameters
rects Rectangles to be removed.
Definition at line 148 of file DirectOptimizer.cpp.
runOptimization()
void DirectOptimizer::runOptimization () override virtual
Starts the optimization using the DIRECT algorithm.
Only returns when an iteration has completed and stopCon deems the optimization complete or when abort was called in the last iteration.
Implements Optimizer.
Definition at line 23 of file DirectOptimizer.cpp.
References Optimizer::getValueMap(), Levels::isGlobal(), iterations, Levels::L3_EPSILON, level, Levels::nextLevel(), printValues, saveProgress(), saveValues(), Levels::setGlobal(), and trackProgress.
saveProgress()
void DirectOptimizer::saveProgress (functionValue bestVal, size_t evaluations, size_t nrRects) const private
Prints the current number of iterations, evaluations, rectangles and the current optimal value to a .csv file.
Parameters
bestVal Value at the current minimum.
evaluations Number of evaluations conducted by the optimization.
nrRects Number of rectangles in the current partition (meaning number of rectangles in activeRects).
Definition at line 159 of file DirectOptimizer.cpp.
Referenced by runOptimization().
saveValues()
void DirectOptimizer::saveValues () private
Prints all evaluated parameterCombinations and their respective values to a .csv file.
Definition at line 171 of file DirectOptimizer.cpp.
Referenced by runOptimization().
Member Data Documentation
activeRects
std::map<depth, std::set<std::shared_ptr<HyRect>, CmpSharedHyrect>, std::greater<> > DirectOptimizer::activeRects private
Holds all rectangles that are immediate part of the current partition.
This includes all rectangles which have not been divided yet. They are grouped by HyRect::t and sorted by HyRect::avgValue which simplifies the search for potentially optimal rectangles in optimalRectangles.
Definition at line 77 of file DirectOptimizer.h.
D
const dimension DirectOptimizer::D private
Number of parameters to be optimized (meaning dimensions of the search space).
Definition at line 44 of file DirectOptimizer.h.
iterations
size_t DirectOptimizer::iterations = 0 private
Number of iterations completed.
Definition at line 48 of file DirectOptimizer.h.
Referenced by getStatus(), and runOptimization().
level
Levels DirectOptimizer::level private
An object used switching between different levels between global and local search.
Definition at line 56 of file DirectOptimizer.h.
Referenced by DirectOptimizer(), getStatus(), and runOptimization().
normalizer
ParameterNormalizer DirectOptimizer::normalizer private
An object used for transformation between the unit hypercube used in DIRECT and the actual parameter space.
Definition at line 60 of file DirectOptimizer.h.
printValues
bool DirectOptimizer::printValues private
Defines if all found values should be recorded in a .csv file after optimization has finished.
Can be set in config.
Definition at line 70 of file DirectOptimizer.h.
Referenced by DirectOptimizer(), and runOptimization().
stopCon
StoppingCondition DirectOptimizer::stopCon private
An object deciding when the optimization stops.
Definition at line 52 of file DirectOptimizer.h.
trackProgress
bool DirectOptimizer::trackProgress private
Defines if the current number of iterations, evaluations, rectangles and the optimal value should be recorded into a .csv file after each iteration.
Can be set in config.
Definition at line 65 of file DirectOptimizer.h.
Referenced by DirectOptimizer(), and runOptimization().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/optimizer/direct/DirectOptimizer.h
/home/runner/work/simopticon/simopticon/src/optimizer/direct/DirectOptimizer.cpp