Simopticon: StubController Class Reference
StubController Class Reference
controller
A class that mocks behaviour of Controller.
#include "StubController.h"
Public Member Functions
StubController (const std::filesystem::path &configPath, const std::string &function)
Creates a StubController with the given config and function.
Public Member Functions inherited from Controller
Controller (const std::filesystem::path &configPath, bool isStub=false)
Creates a Controller which uses Optimizer, SimulationRunner and Evaluation as specified in the given config files.
void run ()
Starts optimization process by calling Optimizer::runOptimization.
std::map< parameterCombination, functionValue > requestValues (const std::list< parameterCombination > &params)
Searches valueMap for results to given parameterCombinations.
ValueMap & getValueMap ()
Returns valueMap.
void abort () override
Aborts optimizer using Optimizer::abort.
Private Member Functions
std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > &runs) override
Returns empty paths and runIds for each requested parameterCombination.
std::map< parameterCombination, functionValue, CmpVectorSharedParameter > evaluate (const std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId >>, CmpVectorSharedParameter > &simulationResults) override
Evaluates the given parameterCombinations with f.
void removeOldResultfiles () override
Does nothing, since no simulations are run and therefore no result files are created.
void updateStatus () override
Updates the statusBar using StatusBar::updateStatus.
Private Attributes
const std::function< functionValue(parameterCombination)> f
Function to be optimized in the current optimization.
Static Private Attributes
static std::map< std::string, std::function< functionValue(parameterCombination)> > functions
Map that contains the predefined functions quadratic, shekel5, shekel7, shekel10, branin, goldprice, camel6, shubert, hartman3 and hartman6.
Additional Inherited Members
Protected Attributes inherited from Controller
StatusBar statusBar
StatusBar object used for output.
std::unique_ptr< Optimizer > optimizer
Optimizer defining an optimization strategy.
std::unique_ptr< SimulationRunner > runner
SimulationRunner able to run simulations with certain parameterCombinations.
std::unique_ptr< Evaluation > evaluation
Evaluation capable of evaluating data produced by runner.
std::unique_ptr< ValueMap > valueMap
ValueMap containing all values gathered by simulating and evaluating certain parameterCombinations.
struct Controller::stepstate stepState
An object keeping track of the current optimization step.
Protected Attributes inherited from Abortable
bool aborted = false
Defines if the process has been aborted, i.e.
Detailed Description
A class that mocks behaviour of Controller.
Instead of real simulations one of the predefined function in functions is being evaluated, when Controller::requestValues is called. To use StubController instead of Controller a second command line argument has to be passed containing the name of the function to be optimized. The name can be one of the following: quadratic, shekel5, shekel7, shekel10, branin, goldprice, camel6, shubert, hartman3 or hartman6. For more information on all but the first function visit: https://www.sfu.ca/~ssurjano/optimization.html
Definition at line 21 of file StubController.h.
Constructor & Destructor Documentation
StubController()
StubController::StubController (const std::filesystem::path & configPath, const std::string & function)
Creates a StubController with the given config and function.
Parameters
configPath Path to the main config. Chosen by first command line argument.
function Name of the function to be used. Chosen by second command line argument.
Definition at line 142 of file StubController.cpp.
References Controller::Controller(), f, and functions.
Member Function Documentation
evaluate()
std::map< parameterCombination, functionValue, CmpVectorSharedParameter > StubController::evaluate (const std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId >>, CmpVectorSharedParameter > & simulationResults) override private virtual
Evaluates the given parameterCombinations with f.
Parameters
simulationResults Map which maps parameterCombinations to empty results (see runSimulations).
Returns
A Map which maps the given parameterCombinations to the respective value of f.
Reimplemented from Controller.
Definition at line 155 of file StubController.cpp.
References f.
removeOldResultfiles()
void StubController::removeOldResultfiles () override private virtual
Does nothing, since no simulations are run and therefore no result files are created.
Reimplemented from Controller.
Definition at line 164 of file StubController.cpp.
runSimulations()
std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > StubController::runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > & runs) override private virtual
Returns empty paths and runIds for each requested parameterCombination.
Parameters
runs parameterCombination to be simulated.
Returns
Map which maps the given parameterCombinations to empty paths and runIds.
Reimplemented from Controller.
Definition at line 147 of file StubController.cpp.
updateStatus()
void StubController::updateStatus () override private virtual
Updates the statusBar using StatusBar::updateStatus.
Reimplemented from Controller.
Definition at line 167 of file StubController.cpp.
References Controller::stepstate::get(), ValueMap::getSize(), ValueMap::getTopVals(), Controller::optimizer, Controller::statusBar, Controller::stepstate::stepChanged, StatusBar::updateStatus(), and Controller::valueMap.
Member Data Documentation
f
const std::function<functionValue(parameterCombination)> StubController::f private
Function to be optimized in the current optimization.
One of the functions in functions.
Definition at line 32 of file StubController.h.
Referenced by StubController(), and evaluate().
functions
std::map< std::string, std::function< functionValue(parameterCombination)> > StubController::functions static private
Map that contains the predefined functions quadratic, shekel5, shekel7, shekel10, branin, goldprice, camel6, shubert, hartman3 and hartman6.
For more information on all but the first function visit: https://www.sfu.ca/~ssurjano/optimization.html
Definition at line 27 of file StubController.h.
Referenced by StubController().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/controller/StubController.h
/home/runner/work/Simopticon/Simopticon/src/controller/StubController.cpp