Simopticon: DiscreteParameter Class Reference
DiscreteParameter Class Reference
parameters
Implements a Parameter using discrete values.
#include "DiscreteParameter.h"
Public Member Functions
DiscreteParameter (shared_ptr< ParameterDefinition > def, double step, double value)
Creates a DiscreteParameter with the given ParameterDefinition, step and value.
DiscreteParameter (shared_ptr< ParameterDefinition > def, double step)
Creates a DiscreteParameter with the given ParameterDefinition and step.
int getTimes () const
Returns the value of times.
void setTimes (int newTimes)
Sets the value of times to the given value.
double getStep () const
Returns the value of step.
double getOffset () const
Returns the value of offset.
coordinate getVal () const override
Returns the current value of the DiscreteParameter as calculated by the following formula: .
void setVal (coordinate val) override
Sets the value of the DiscreteParameter to the discrete value closest to the given value by modifying times using setTimes.
Public Member Functions inherited from Parameter
Parameter (shared_ptr< ParameterDefinition > def)
Creates a Parameter with the given ParameterDefinition.
coordinate getMin () const
Returns the minimum value of the Parameter stored in ParameterDefinition::min of definition.
coordinate getMax () const
Returns the maximum value of the Parameter stored in ParameterDefinition::max of definition.
const string & getUnit () const
Returns the unit string of the Parameter stored in ParameterDefinition::unit of definition.
const string & getConfig () const
Returns the configuration string of the Parameter stored in ParameterDefinition::config of definition.
bool operator== (const Parameter &rhs) const
Checks if the current and the given Parameter objects are equal by comparing their value and definition.
bool operator!= (const Parameter &rhs) const
Checks if the current and the given Parameter objects are unequal by comparing their value and definition.
bool operator< (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator> (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator<= (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator>= (const Parameter &rhs) const
Compares the value of the given Parameter objects.
Private Attributes
int times
Times used in the value calculation.
double step
Difference between discrete values.
double offset = 0
Offset used in the value calculation.
Detailed Description
Implements a Parameter using discrete values.
The value of the Parameter is calculated as .
Definition at line 12 of file DiscreteParameter.h.
Constructor & Destructor Documentation
DiscreteParameter() [1/2]
DiscreteParameter::DiscreteParameter (shared_ptr< ParameterDefinition > def, double step, double value)
Creates a DiscreteParameter with the given ParameterDefinition, step and value.
Checks if given value is in bounds set by the ParameterDefinition. Calculates times and offset automatically.
Parameters
def ParameterDefinition of the Parameter.
step Difference between discrete values.
value Initial value of the Parameter.
Definition at line 7 of file DiscreteParameter.cpp.
References Parameter::Parameter(), Parameter::getMax(), Parameter::getMin(), offset, step, and times.
Referenced by DiscreteParameter().
DiscreteParameter() [2/2]
DiscreteParameter::DiscreteParameter (shared_ptr< ParameterDefinition > def, double step)
Creates a DiscreteParameter with the given ParameterDefinition and step.
Calculates times and offset automatically.
Parameters
def ParameterDefinition of the Parameter.
step Difference between discrete values.
Definition at line 17 of file DiscreteParameter.cpp.
References DiscreteParameter(), Parameter::getMax(), and Parameter::getMin().
Member Function Documentation
getOffset()
double DiscreteParameter::getOffset () const
Returns the value of offset.
Returns
A floating point number representing the offset.
Definition at line 37 of file DiscreteParameter.cpp.
References offset.
getStep()
double DiscreteParameter::getStep () const
Returns the value of step.
Returns
A floating point number representing the difference between discrete values.
Definition at line 33 of file DiscreteParameter.cpp.
References step.
getTimes()
int DiscreteParameter::getTimes () const
Returns the value of times.
Returns
An integer representing the times value.
Definition at line 21 of file DiscreteParameter.cpp.
References times.
getVal()
coordinate DiscreteParameter::getVal () const override virtual
Returns the current value of the DiscreteParameter as calculated by the following formula: .
Returns
A coordinate representing the value of the ContinuousParameter.
Implements Parameter.
Definition at line 41 of file DiscreteParameter.cpp.
References offset, step, and times.
setTimes()
void DiscreteParameter::setTimes (int newTimes)
Sets the value of times to the given value.
Checks if value is in bounds set by ParameterDefinition.
Parameters
newTimes
Definition at line 25 of file DiscreteParameter.cpp.
References Parameter::getMax(), Parameter::getMin(), offset, step, and times.
Referenced by setVal().
setVal()
void DiscreteParameter::setVal (coordinate val) override virtual
Sets the value of the DiscreteParameter to the discrete value closest to the given value by modifying times using setTimes.
Parameters
val Value to set the DiscreteParameter to.
Implements Parameter.
Definition at line 45 of file DiscreteParameter.cpp.
References offset, setTimes(), and step.
Member Data Documentation
offset
double DiscreteParameter::offset = 0 private
Offset used in the value calculation.
Definition at line 25 of file DiscreteParameter.h.
Referenced by DiscreteParameter(), getOffset(), getVal(), setTimes(), and setVal().
step
double DiscreteParameter::step private
Difference between discrete values.
Used in the value calculation.
Definition at line 21 of file DiscreteParameter.h.
Referenced by DiscreteParameter(), getStep(), getVal(), setTimes(), and setVal().
times
int DiscreteParameter::times private
Times used in the value calculation.
Definition at line 17 of file DiscreteParameter.h.
Referenced by DiscreteParameter(), getTimes(), getVal(), and setTimes().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/parameters/DiscreteParameter.h
/home/runner/work/simopticon/simopticon/src/parameters/DiscreteParameter.cpp