Simopticon: DirectStoppingCondition Class Reference
DirectStoppingCondition Class Reference
optimizer » direct
A class used for deciding whether the DIRECT should be stopped.
#include "DirectStoppingCondition.h"
Public Member Functions
DirectStoppingCondition (size_t evaluations=0, size_t hyrects=0, unsigned int minutes=0, functionValue accuracy=0, unsigned int accuracyIterations=0)
Creates a StoppingCondition with the given condition values.
DirectStoppingCondition (const nlohmann::json &stopCon)
Creates a StoppingCondition based on the given json configuration.
bool evaluate (size_t evaluations, size_t hyrects, functionValue newBestVal)
Checks if any of the configured conditions is met for the given parameters.
Public Member Functions inherited from StoppingCondition
StoppingCondition (size_t evaluations=0, unsigned int minutes=0, functionValue accuracy=0, unsigned int accuracyIterations=0)
Creates a StoppingCondition with the given condition values.
StoppingCondition (nlohmann::json stopCon)
Creates a StoppingCondition based on the given json configuration.
void setStartNow ()
Sets END_TIME to be the current time plus mins.
bool evaluate (size_t evaluations, functionValue newBestVal)
Checks if any of the configured conditions is met for the given parameters.
unsigned int getIterationsSinceImprov () const
Returns the value of iterationsSinceImprov.
Private Attributes
const size_t NR_HYRECTS
Number of rectangles in the partition after which the optimization should stop.
Additional Inherited Members
Static Protected Member Functions inherited from StoppingCondition
template<typename T >
static T getConditionFromJSON (nlohmann::json object, const std::string &key, const std::string &val="n")
Helper method, which checks whether the given condition should be used and returns the corresponding value if thats the case.
Detailed Description
A class used for deciding whether the DIRECT should be stopped.
Every conditions is optional and can be set in config. The optimization is stopped when one of the activated conditions is met.
Author
Per Natzschka
Definition at line 22 of file DirectStoppingCondition.h.
Constructor & Destructor Documentation
DirectStoppingCondition() [1/2]
DirectStoppingCondition::DirectStoppingCondition (size_t evaluations = 0, size_t hyrects = 0, unsigned int minutes = 0, functionValue accuracy = 0, unsigned int accuracyIterations = 0) explicit
Creates a StoppingCondition with the given condition values.
Parameters
evaluations Number of evaluations after which the optimization should stop.
hyrects Number of rectangles in the partition after which the optimization should stop.
minutes Number of minutes after which the optimization should stop.
accuracy Accuracy used in accuracy condition (see ACCURACY).
accuracyIterations Number of iterations used in accuracy condition (see NR_ACCURACY_ITERATIONS).
Definition at line 9 of file DirectStoppingCondition.cpp.
References StoppingCondition::StoppingCondition(), and NR_HYRECTS.
DirectStoppingCondition() [2/2]
DirectStoppingCondition::DirectStoppingCondition (const nlohmann::json & stopCon) explicit
Creates a StoppingCondition based on the given json configuration.
Parameters
stopCon JSON object defining the condition values.
Definition at line 16 of file DirectStoppingCondition.cpp.
References DirectStoppingCondition().
Referenced by DirectStoppingCondition().
Member Function Documentation
evaluate()
bool DirectStoppingCondition::evaluate (size_t evaluations, size_t hyrects, functionValue newBestVal)
Checks if any of the configured conditions is met for the given parameters.
Parameters
evaluations Number of evaluations conducted by the optimization.
hyrects Number of rectangles in the current partition.
newBestVal Value of the current optimum.
Returns
A boolean defining whether none of the configured conditions is met (meaning whether the optimization should keep running).
Definition at line 22 of file DirectStoppingCondition.cpp.
References StoppingCondition::evaluate(), and NR_HYRECTS.
Member Data Documentation
NR_HYRECTS
const size_t DirectStoppingCondition::NR_HYRECTS private
Number of rectangles in the partition after which the optimization should stop.
Definition at line 27 of file DirectStoppingCondition.h.
Referenced by DirectStoppingCondition(), and evaluate().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/optimizer/direct/DirectStoppingCondition.h
/home/runner/work/Simopticon/Simopticon/src/optimizer/direct/DirectStoppingCondition.cpp