Simopticon: PlexeSimulationRunner Class Reference
PlexeSimulationRunner Class Reference
runner » plexe
A class capable of starting platooning simulations in the Plexe framework with given parameterCombinations.
#include "PlexeSimulationRunner.h"
Public Member Functions
PlexeSimulationRunner (unsigned int threads, unsigned int repeat, std::vector< std::string > scenarios, ConfigEditor editor)
Creates PlexeSimulationRunner which cannot use more than the given number of threads.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from SimulationRunner
SimulationRunner (unsigned int threads)
Creates a SimulationRunner which can use no more than the given number of threads to simulate parameterCombinations concurrently.
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > &runs)
Simulates the given parameterCombinations concurrently and returns their respective results.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >
Multithreaded (unsigned int threads)
Creates a Multithreaded class that does not use more than the given number of threads.
Public Member Functions inherited from Multithreaded< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool >
Multithreaded (unsigned int threads)
Creates a Multithreaded class that does not use more than the given number of threads.
Private Member Functions
size_t getRunId ()
Returns an unique number which can be used to identify the results of a certain parameterCombination.
std::pair< std::filesystem::path, std::set< runId > > work (parameterCombination run) override
Runs simulations for the given parameterCombination.
bool work (std::pair< std::filesystem::path, std::pair< std::basic_string< char >, unsigned int >> arg) override
Executes one run of a parameterCombination (meaning repetition k of scenario c).
Private Attributes
const unsigned int REPEAT
Number of repetitions per parameterCombination and scenario in SCENARIOS.
const std::vector< std::string > SCENARIOS
Scenarios that are simulated per parameterCombination.
ConfigEditor editor
ConfigEditor used for automatically creating .ini files with given Parameter settings.
size_t runNumber = 0
Identifier for each simulated parameterCombination.
std::mutex runNumberLock
Threadlock to prevent race conditions on concurrent access of runNumber.
Additional Inherited Members
Protected Member Functions inherited from Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter, std::allocator< std::pair< const parameterCombination, std::pair< std::filesystem::path, std::set< runId > > >> > runMultithreadedFunctions (std::set< parameterCombination, CmpVectorSharedParameter > runs)
Pushes given tasks into queue, creates concurrent threads and merges them when execution is done.
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter, std::allocator< std::pair< const parameterCombination, std::pair< std::filesystem::path, std::set< runId > > >> > multithreadFunction ()
Function that is executed by each thread.
Protected Member Functions inherited from Multithreaded< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool >
virtual std::map< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool, std::less< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > > >, std::allocator< std::pair< const std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool >> > runMultithreadedFunctions (std::set< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, std::less< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > > > > runs)
Pushes given tasks into queue, creates concurrent threads and merges them when execution is done.
virtual std::map< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool, std::less< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > > >, std::allocator< std::pair< const std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool >> > multithreadFunction ()
Function that is executed by each thread.
Protected Attributes inherited from Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >
const unsigned int NR_THREADS
Maximum number of concurrent threads to be used in ThreadPool.
ThreadsafeQueue< parameterCombination > queue
ThreadsafeQueue containing the arguments that have to be processed by the ThreadPool.
Protected Attributes inherited from Multithreaded< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > >, bool >
const unsigned int NR_THREADS
Maximum number of concurrent threads to be used in ThreadPool.
ThreadsafeQueue< std::pair< std::filesystem::path, std::pair< std::string, unsigned int > > > queue
ThreadsafeQueue containing the arguments that have to be processed by the ThreadPool.
Static Protected Attributes inherited from Status
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class capable of starting platooning simulations in the Plexe framework with given parameterCombinations.
Definition at line 30 of file PlexeSimulationRunner.h.
Constructor & Destructor Documentation
PlexeSimulationRunner()
PlexeSimulationRunner::PlexeSimulationRunner (unsigned int threads, unsigned int repeat, std::vector< std::string > scenarios, ConfigEditor editor)
Creates PlexeSimulationRunner which cannot use more than the given number of threads.
Number of repetitions, scenarios to be simulated and the ConfigEditor must also be defined. The new PlexeSimulationRunner uses concurrent threads for parallelization of work(std::pair< std::filesystem::path, std::pair< std::basic_string< char >, unsigned int >>). For the parallelization of work(parameterCombination) concurrent threads are used.
Parameters
threads Maximum number of threads to be used.
repeat Number of repetitions per parameterCombination and scenario.
scenarios Scenarios to be simulated per parameterCombination.
editor ConfigEditor to be used.
Definition at line 14 of file PlexeSimulationRunner.cpp.
References PlexeSimulationRunner(), and REPEAT.
Referenced by PlexeSimulationRunner().
Member Function Documentation
getName()
std::string PlexeSimulationRunner::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 82 of file PlexeSimulationRunner.cpp.
getRunId()
size_t PlexeSimulationRunner::getRunId () private
Returns an unique number which can be used to identify the results of a certain parameterCombination.
Returned value is only unique for one optimization process. Basically increments runNumber and returns value before incrementation.
Returns
An unique number used for discerning results of different runs.
Definition at line 58 of file PlexeSimulationRunner.cpp.
References runNumber, and runNumberLock.
Referenced by work().
getStatus()
std::string PlexeSimulationRunner::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 86 of file PlexeSimulationRunner.cpp.
References REPEAT, and runNumber.
getStatusBar()
std::string PlexeSimulationRunner::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 99 of file PlexeSimulationRunner.cpp.
work() [1/2]
std::pair< std::filesystem::path, std::set< runId > > PlexeSimulationRunner::work (parameterCombination run) override private virtual
Runs simulations for the given parameterCombination.
Creates a new .ini file for the parameterCombination. Parallelizes the execution of different scenarios (see SCENARIOS) and their repetitions (see REPEAT) using Multithreaded class. Parallelized function is defined in work(std::pair< std::filesystem::path, std::pair< std::basic_string< char >, unsigned int >>).
Parameters
run parameterCombination to be simulated.
Returns
A pair containing the path to the result files and OMNeT++-Run-IDs of the executed simulations.
Implements SimulationRunner.
Definition at line 23 of file PlexeSimulationRunner.cpp.
References getRunId().
work() [2/2]
bool PlexeSimulationRunner::work (std::pair< std::filesystem::path, std::pair< std::basic_string< char >, unsigned int >> arg) override private
Executes one run of a parameterCombination (meaning repetition k of scenario c).
Runs command for starting Plexe and returns after execution is done.
Parameters
arg A triple containing the path to the .ini defining the parameters, the scenario name and the repetition number.
Returns
A boolean defining whether the execution ran without throwing exceptions.
Definition at line 67 of file PlexeSimulationRunner.cpp.
Member Data Documentation
editor
ConfigEditor PlexeSimulationRunner::editor private
ConfigEditor used for automatically creating .ini files with given Parameter settings.
Definition at line 47 of file PlexeSimulationRunner.h.
REPEAT
const unsigned int PlexeSimulationRunner::REPEAT private
Number of repetitions per parameterCombination and scenario in SCENARIOS.
Translates to repeat setting in omnetpp.ini. Can be set in configuration.
Definition at line 37 of file PlexeSimulationRunner.h.
Referenced by PlexeSimulationRunner(), and getStatus().
runNumber
size_t PlexeSimulationRunner::runNumber = 0 private
Identifier for each simulated parameterCombination.
Is incremented when new parameterCombination is simulated. Used for unique directory names for result files.
Definition at line 53 of file PlexeSimulationRunner.h.
Referenced by getRunId(), and getStatus().
runNumberLock
std::mutex PlexeSimulationRunner::runNumberLock private
Threadlock to prevent race conditions on concurrent access of runNumber.
Definition at line 57 of file PlexeSimulationRunner.h.
Referenced by getRunId().
SCENARIOS
const std::vector<std::string> PlexeSimulationRunner::SCENARIOS private
Scenarios that are simulated per parameterCombination.
Should not invoke a GUI (e.g. pick BrakingNoGui instead of Braking). Can be set in configuration.
Definition at line 42 of file PlexeSimulationRunner.h.
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/runner/plexe/PlexeSimulationRunner.h
/home/runner/work/simopticon/simopticon/src/runner/plexe/PlexeSimulationRunner.cpp