Simopticon: GrahamScan Class Reference
GrahamScan Class Reference
Optimizer » Direct
A class providing functionality for finding the lower right convex hull of a set of points.
#include "GrahamScan.h"
Static Public Member Functions
static list< pair< shared_ptr< HyRect >, double > > scan (list< shared_ptr< HyRect >> vertices)
Calculates the lower right convex hull of a set of points.
Detailed Description
A class providing functionality for finding the lower right convex hull of a set of points.
Definition at line 15 of file GrahamScan.h.
Member Function Documentation
scan()
list< pair< shared_ptr< HyRect >, double > > GrahamScan::scan (list< shared_ptr< HyRect >> vertices) static
Calculates the lower right convex hull of a set of points.
Points are defined by the given HyRects diagonal length (x axis) and average value (y axis). For each returned HyRect the slope to the point right of it is returned (if it is the rightmost point, infinity is chosen). That slope value can be used by DIRECT as the highest Lipschitz constant for which the HyRect satisfies the first condition.
Parameters
vertices List of rectangles with different sizes.
Returns
A list of rectangles and corresponding Lipschitz constants that represents convex hull meaning a subset of the given HyRect list.
Definition at line 7 of file GrahamScan.cpp.
References HyRect::getAvgValue(), HyRect::getDepth(), and HyRect::getDiagonalLength().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/optimizer/direct/GrahamScan.h
/home/runner/work/simopticon/simopticon/src/optimizer/direct/GrahamScan.cpp