Simopticon: Parameter Class Reference
Parameter Class Reference abstract
parameters
A class acting as the container of the value of a parameter defined by a ParameterDefinition.
#include "Parameter.h"
Public Member Functions
Parameter (std::shared_ptr< ParameterDefinition > def)
Creates a Parameter with the given ParameterDefinition.
coordinate getMin () const
Returns the minimum value of the Parameter stored in ParameterDefinition::min of definition.
coordinate getMax () const
Returns the maximum value of the Parameter stored in ParameterDefinition::max of definition.
const std::string & getUnit () const
Returns the unit string of the Parameter stored in ParameterDefinition::unit of definition.
const std::string & getConfig () const
Returns the configuration string of the Parameter stored in ParameterDefinition::config of definition.
virtual coordinate getVal () const =0
Returns the current value of the Parameter.
virtual void setVal (coordinate val)=0
Sets the value of the Parameter to the given value.
bool operator== (const Parameter &rhs) const
Checks if the current and the given Parameter objects are equal by comparing their value and definition.
bool operator!= (const Parameter &rhs) const
Checks if the current and the given Parameter objects are unequal by comparing their value and definition.
bool operator< (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator> (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator<= (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator>= (const Parameter &rhs) const
Compares the value of the given Parameter objects.
Private Attributes
std::shared_ptr< ParameterDefinition > definition
Reference to the defining ParameterDefinition.
Detailed Description
A class acting as the container of the value of a parameter defined by a ParameterDefinition.
Definition at line 30 of file Parameter.h.
Constructor & Destructor Documentation
Parameter()
Parameter::Parameter (std::shared_ptr< ParameterDefinition > def) explicit
Creates a Parameter with the given ParameterDefinition.
Parameters
def Definition of properties of the Parameter.
Definition at line 12 of file Parameter.cpp.
References definition.
Referenced by ContinuousParameter::ContinuousParameter(), and DiscreteParameter::DiscreteParameter().
Member Function Documentation
getConfig()
const std::string & Parameter::getConfig () const
Returns the configuration string of the Parameter stored in ParameterDefinition::config of definition.
Returns
A string reference containing the configuration.
Definition at line 28 of file Parameter.cpp.
References definition, and ParameterDefinition::getConfig().
Referenced by StatusBar::printResult().
getMax()
coordinate Parameter::getMax () const
Returns the maximum value of the Parameter stored in ParameterDefinition::max of definition.
Returns
A coordinate representing the maximum value.
Definition at line 20 of file Parameter.cpp.
References definition, and ParameterDefinition::getMax().
Referenced by ContinuousParameter::ContinuousParameter(), DiscreteParameter::DiscreteParameter(), ParameterNormalizer::normalize(), DiscreteParameter::setTimes(), and ContinuousParameter::setVal().
getMin()
coordinate Parameter::getMin () const
Returns the minimum value of the Parameter stored in ParameterDefinition::min of definition.
Returns
A coordinate representing the minimum value.
Definition at line 16 of file Parameter.cpp.
References definition, and ParameterDefinition::getMin().
Referenced by ContinuousParameter::ContinuousParameter(), DiscreteParameter::DiscreteParameter(), ParameterNormalizer::normalize(), DiscreteParameter::setTimes(), and ContinuousParameter::setVal().
getUnit()
const std::string & Parameter::getUnit () const
Returns the unit string of the Parameter stored in ParameterDefinition::unit of definition.
Returns
A string reference containing the unit.
Definition at line 24 of file Parameter.cpp.
References definition, and ParameterDefinition::getUnit().
Referenced by StatusBar::printResult().
getVal()
virtual coordinate Parameter::getVal () const pure virtual
Returns the current value of the Parameter.
Returns
A coordinate representing the value of the Parameter.
Implemented in DiscreteParameter, and ContinuousParameter.
Referenced by ValueMap::isTopValue(), ParameterNormalizer::normalize(), operator<(), operator==(), and StatusBar::printResult().
operator!=()
bool Parameter::operator!= (const Parameter & rhs) const
Checks if the current and the given Parameter objects are unequal by comparing their value and definition.
Basically negates operator==.
Parameters
rhs Parameter to be compared.
Returns
A boolean defining if the Parameter objects contain another value or another definition.
Definition at line 36 of file Parameter.cpp.
References operator==().
Referenced by CmpVectorSharedParameter::operator()().
operator<()
bool Parameter::operator< (const Parameter & rhs) const
Compares the value of the given Parameter objects.
Parameters
rhs Parameter to be compared.
Returns
A boolean defining if the value of this Parameter is less than that of the given Parameter.
Definition at line 40 of file Parameter.cpp.
References getVal().
Referenced by CmpVectorSharedParameter::operator()(), operator<=(), operator>(), and operator>=().
operator<=()
bool Parameter::operator<= (const Parameter & rhs) const
Compares the value of the given Parameter objects.
Basically negates operator<.
Parameters
rhs Parameter to be compared.
Returns
A boolean defining if the value of this Parameter is less than or equal to that of the given Parameter.
Definition at line 48 of file Parameter.cpp.
References operator<().
operator==()
bool Parameter::operator== (const Parameter & rhs) const
Checks if the current and the given Parameter objects are equal by comparing their value and definition.
Parameters
rhs Parameter to be compared.
Returns
A boolean defining if the Parameter objects contain the same value for the same definition.
Definition at line 32 of file Parameter.cpp.
References definition, and getVal().
Referenced by operator!=().
operator>()
bool Parameter::operator> (const Parameter & rhs) const
Compares the value of the given Parameter objects.
Basically calls operator< on the switched inputs.
Parameters
rhs Parameter to be compared.
Returns
A boolean defining if the value of this Parameter is greater than that of the given Parameter.
Definition at line 44 of file Parameter.cpp.
References operator<().
operator>=()
bool Parameter::operator>= (const Parameter & rhs) const
Compares the value of the given Parameter objects.
Basically negates operator>.
Parameters
rhs Parameter to be compared.
Returns
A boolean defining if the value of this Parameter is greater than or equal to that of the given Parameter.
Definition at line 52 of file Parameter.cpp.
References operator<().
setVal()
virtual void Parameter::setVal (coordinate val) pure virtual
Sets the value of the Parameter to the given value.
Parameters
val Value to set the Parameter to.
Implemented in DiscreteParameter, and ContinuousParameter.
Member Data Documentation
definition
std::shared_ptr<ParameterDefinition> Parameter::definition private
Reference to the defining ParameterDefinition.
Definition at line 35 of file Parameter.h.
Referenced by Parameter(), getConfig(), getMax(), getMin(), getUnit(), and operator==().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/parameters/Parameter.h
/home/runner/work/Simopticon/Simopticon/src/parameters/Parameter.cpp