Simopticon: ConfigEditor Class Reference
ConfigEditor Class Reference
runner » plexe
A class capable of creating .ini files with certain options based on a complete omnetpp.ini.
#include "ConfigEditor.h"
Public Member Functions
ConfigEditor (std::filesystem::path directory, nlohmann::json controller)
Creates a ConfigEditor that creates config files in the given directory for simulation of the given controller.
void createConfig (const parameterCombination &params, size_t runNumber, unsigned int repeat)
Copies the config at CONFIG to a file .tmpx.ini where x is given by runNumber and edits the file for the purposes of the optimization.
void deleteConfig (size_t runId) const
Deletes the file .tmpx.ini from DIR where x is given by runId.
const std::filesystem::path & getDir () const
Returns the directory of the Plexe configuration.
std::filesystem::path getConfigPath (size_t runId) const
Returns the path to the created config for the parameterCombination with the given number.
std::filesystem::path getResultPath (size_t runId) const
Returns the path to the result files generated by simulating the parameterCombination with the given number.
Private Member Functions
void setResultFiles (std::string &file, size_t runNumber)
Sets all output directories in the given file to a directory that is named after the given number and a subdirectory of RESULTS.
Static Private Member Functions
static void replaceOption (std::string &file, std::string option, const std::string &value)
Replaces the value of the given key with the given new value in the given string.
static void replaceOption (std::string &file, std::string option, long value)
Replaces the value of the given key with the given new value in the given string.
static std::string getControllerOption (std::string &file)
Returns the key that defines the used controller in the given .ini file.
Private Attributes
const std::filesystem::path DIR
Path to a directory containing a complete configuration of Plexe.
const std::filesystem::path CONFIG
Path to the omnetpp.ini file in DIR.
const std::filesystem::path RESULTS
Path to the optResults directory in DIR where the simulation result files are generated.
const nlohmann::json CONTROLLER
Configuration of the controller to be simulated.
Detailed Description
A class capable of creating .ini files with certain options based on a complete omnetpp.ini.
Definition at line 24 of file ConfigEditor.h.
Constructor & Destructor Documentation
ConfigEditor()
ConfigEditor::ConfigEditor (std::filesystem::path directory, nlohmann::json controller)
Creates a ConfigEditor that creates config files in the given directory for simulation of the given controller.
Parameters
directory A path to the directory containing a Plexe configuration.
controller A json object configuring the controller to be simulated.
Definition at line 11 of file ConfigEditor.cpp.
References ConfigEditor().
Referenced by ConfigEditor().
Member Function Documentation
createConfig()
void ConfigEditor::createConfig (const parameterCombination & params, size_t runNumber, unsigned int repeat)
Copies the config at CONFIG to a file .tmpx.ini where x is given by runNumber and edits the file for the purposes of the optimization.
Sets the values of optimized parameters, controller, result directory and some options minimizing output of Plexe.
Parameters
params The parameterCombination to be simulated.
runNumber An unique number of the simulated parameterCombination.
repeat Number of repetitions to be simulated.
Definition at line 16 of file ConfigEditor.cpp.
References setResultFiles().
deleteConfig()
void ConfigEditor::deleteConfig (size_t runId) const
Deletes the file .tmpx.ini from DIR where x is given by runId.
Parameters
runId Number of the configuration file to be deleted.
Definition at line 95 of file ConfigEditor.cpp.
References getConfigPath().
getConfigPath()
std::filesystem::path ConfigEditor::getConfigPath (size_t runId) const
Returns the path to the created config for the parameterCombination with the given number.
Parameters
runId Number of the parameterCombination.
Returns
A path to the config for the given runId.
Definition at line 85 of file ConfigEditor.cpp.
Referenced by deleteConfig().
getControllerOption()
std::string ConfigEditor::getControllerOption (std::string & file) static private
Returns the key that defines the used controller in the given .ini file.
That is necessary for backwards compatability reasons because said key changed in Plexe 3.1.
Parameters
file A string containing the contents of an .ini file.
Returns
A string containing the key where the used controller is defined.
Definition at line 74 of file ConfigEditor.cpp.
getDir()
const std::filesystem::path & ConfigEditor::getDir () const
Returns the directory of the Plexe configuration.
Returns
The path stored in DIR
Definition at line 99 of file ConfigEditor.cpp.
getResultPath()
std::filesystem::path ConfigEditor::getResultPath (size_t runId) const
Returns the path to the result files generated by simulating the parameterCombination with the given number.
Parameters
runId Number of the parameterCombination.
Returns
A path to the result files for the given runId.
Definition at line 90 of file ConfigEditor.cpp.
replaceOption() [1/2]
void ConfigEditor::replaceOption (std::string & file, std::string option, const std::string & value) static private
Replaces the value of the given key with the given new value in the given string.
Parameters
file A string containing the contents of an .ini file.
option A string representing a key in the given file.
value The new value of the given option in the given file.
Definition at line 47 of file ConfigEditor.cpp.
replaceOption() [2/2]
void ConfigEditor::replaceOption (std::string & file, std::string option, long value) static private
Replaces the value of the given key with the given new value in the given string.
Basically parses the given value to string and calls replaceOption(std::string &, std::string, const std::string &).
Parameters
file A string containing the contents of an .ini file.
option A string representing a key in the given file.
value The new value of the given option in the given file.
Definition at line 61 of file ConfigEditor.cpp.
setResultFiles()
void ConfigEditor::setResultFiles (std::string & file, size_t runNumber) private
Sets all output directories in the given file to a directory that is named after the given number and a subdirectory of RESULTS.
Parameters
file A string containing the contents of an .ini file.
runNumber The unique number of the parameterCombination.
Definition at line 65 of file ConfigEditor.cpp.
Referenced by createConfig().
Member Data Documentation
CONFIG
const std::filesystem::path ConfigEditor::CONFIG private
Path to the omnetpp.ini file in DIR.
Definition at line 34 of file ConfigEditor.h.
CONTROLLER
const nlohmann::json ConfigEditor::CONTROLLER private
Configuration of the controller to be simulated.
Can be set in config.
Definition at line 43 of file ConfigEditor.h.
DIR
const std::filesystem::path ConfigEditor::DIR private
Path to a directory containing a complete configuration of Plexe.
Can be set in config.
Definition at line 30 of file ConfigEditor.h.
RESULTS
const std::filesystem::path ConfigEditor::RESULTS private
Path to the optResults directory in DIR where the simulation result files are generated.
Definition at line 38 of file ConfigEditor.h.
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/runner/plexe/ConfigEditor.h
/home/runner/work/Simopticon/Simopticon/src/runner/plexe/ConfigEditor.cpp