Simopticon: SimulationRunner Class Reference
SimulationRunner Class Reference abstract
runner
A class capable of running simulations with certain parameterCombinations.
#include "SimulationRunner.h"
Public Member Functions
SimulationRunner (unsigned int threads)
Creates a SimulationRunner which can use no more than the given number of threads to simulate parameterCombinations concurrently.
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > &runs)
Simulates the given parameterCombinations concurrently and returns their respective results.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >
Multithreaded (unsigned int threads)
Creates a Multithreaded class that does not use more than the given number of threads.
Private Member Functions
std::pair< std::filesystem::path, std::set< runId > > work (parameterCombination run) override=0
Deals with the simulation of a single parameterCombination.
Additional Inherited Members
Protected Member Functions inherited from Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter, std::allocator< std::pair< const parameterCombination, std::pair< std::filesystem::path, std::set< runId > > >> > runMultithreadedFunctions (std::set< parameterCombination, CmpVectorSharedParameter > runs)
Pushes given tasks into queue, creates concurrent threads and merges them when execution is done.
virtual std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter, std::allocator< std::pair< const parameterCombination, std::pair< std::filesystem::path, std::set< runId > > >> > multithreadFunction ()
Function that is executed by each thread.
Protected Attributes inherited from Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >
const unsigned int NR_THREADS
Maximum number of concurrent threads to be used in ThreadPool.
ThreadsafeQueue< parameterCombination > queue
ThreadsafeQueue containing the arguments that have to be processed by the ThreadPool.
Static Protected Attributes inherited from Status
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class capable of running simulations with certain parameterCombinations.
Definition at line 38 of file SimulationRunner.h.
Constructor & Destructor Documentation
SimulationRunner()
SimulationRunner::SimulationRunner (unsigned int threads) explicit
Creates a SimulationRunner which can use no more than the given number of threads to simulate parameterCombinations concurrently.
Parameters
threads Maximum number of threads that may be used for concurrent simulations.
Definition at line 11 of file SimulationRunner.cpp.
References Multithreaded< Key, T, Compare, Allocator >::Multithreaded().
Member Function Documentation
getName()
std::string SimulationRunner::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 19 of file SimulationRunner.cpp.
References Status::getName().
getStatus()
std::string SimulationRunner::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 23 of file SimulationRunner.cpp.
References Status::getStatus().
getStatusBar()
std::string SimulationRunner::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 27 of file SimulationRunner.cpp.
References Status::getStatusBar().
runSimulations()
std::map< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter > SimulationRunner::runSimulations (const std::set< parameterCombination, CmpVectorSharedParameter > & runs) virtual
Simulates the given parameterCombinations concurrently and returns their respective results.
Basically calls Multithreaded::runMultithreadedFunctions which uses the ThreadPool pattern to parallelize the execution of work.
Parameters
runs Set of parameterCombinations to be simulated.
Returns
A map which maps the given parameterCombinations to their respective result directory and runIds.
Definition at line 15 of file SimulationRunner.cpp.
References Multithreaded< Key, T, Compare, Allocator >::runMultithreadedFunctions().
work()
std::pair<std::filesystem::path, std::set<runId> > SimulationRunner::work (parameterCombination run) override private pure virtual
Deals with the simulation of a single parameterCombination.
Overrides Multithreaded::work and therefore can be executed concurrently.
Parameters
run parameterCombination to be simulated.
Returns
A pair containing a path to the result directory and a set of runIds identifying the respective simulation runs.
Implements Multithreaded< parameterCombination, std::pair< std::filesystem::path, std::set< runId > >, CmpVectorSharedParameter >.
Implemented in PlexeSimulationRunner.
The documentation for this class was generated from the following files:
src/runner/SimulationRunner.h
src/runner/SimulationRunner.cpp