Simopticon: ContinuousParameter Class Reference
ContinuousParameter Class Reference
parameters
Implements a Parameter using continuos values in the form of floating point numbers.
#include "ContinuousParameter.h"
Public Member Functions
ContinuousParameter (shared_ptr< ParameterDefinition > def, coordinate value)
Creates a ContinuousParameter with the given ParameterDefinition and value.
ContinuousParameter (shared_ptr< ParameterDefinition > def)
Creates a ContinuousParameter with the given ParameterDefinition and the initial value being the mean between minimum and maximum.
coordinate getVal () const override
Returns the current value of val.
void setVal (coordinate val) override
Sets the value of val to the given value.
Public Member Functions inherited from Parameter
Parameter (shared_ptr< ParameterDefinition > def)
Creates a Parameter with the given ParameterDefinition.
coordinate getMin () const
Returns the minimum value of the Parameter stored in ParameterDefinition::min of definition.
coordinate getMax () const
Returns the maximum value of the Parameter stored in ParameterDefinition::max of definition.
const string & getUnit () const
Returns the unit string of the Parameter stored in ParameterDefinition::unit of definition.
const string & getConfig () const
Returns the configuration string of the Parameter stored in ParameterDefinition::config of definition.
bool operator== (const Parameter &rhs) const
Checks if the current and the given Parameter objects are equal by comparing their value and definition.
bool operator!= (const Parameter &rhs) const
Checks if the current and the given Parameter objects are unequal by comparing their value and definition.
bool operator< (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator> (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator<= (const Parameter &rhs) const
Compares the value of the given Parameter objects.
bool operator>= (const Parameter &rhs) const
Compares the value of the given Parameter objects.
Private Attributes
coordinate val
Value of the ContinuousParameter.
Detailed Description
Implements a Parameter using continuos values in the form of floating point numbers.
Definition at line 11 of file ContinuousParameter.h.
Constructor & Destructor Documentation
ContinuousParameter() [1/2]
ContinuousParameter::ContinuousParameter (shared_ptr< ParameterDefinition > def, coordinate value)
Creates a ContinuousParameter with the given ParameterDefinition and value.
Checks if given value is in bounds set by the ParameterDefinition.
Parameters
def ParameterDefinition of the Parameter.
value Initial value of the Parameter.
Definition at line 6 of file ContinuousParameter.cpp.
References Parameter::Parameter(), Parameter::getMax(), Parameter::getMin(), and val.
Referenced by ContinuousParameter(), and ParameterNormalizer::denormalize().
ContinuousParameter() [2/2]
ContinuousParameter::ContinuousParameter (shared_ptr< ParameterDefinition > def) explicit
Creates a ContinuousParameter with the given ParameterDefinition and the initial value being the mean between minimum and maximum.
Parameters
def ParameterDefinition of the Parameter.
Definition at line 14 of file ContinuousParameter.cpp.
References ContinuousParameter(), Parameter::getMax(), and Parameter::getMin().
Member Function Documentation
getVal()
coordinate ContinuousParameter::getVal () const override virtual
Returns the current value of val.
Returns
A coordinate representing the value of the ContinuousParameter.
Implements Parameter.
Definition at line 19 of file ContinuousParameter.cpp.
References val.
setVal()
void ContinuousParameter::setVal (coordinate val) override virtual
Sets the value of val to the given value.
Checks if given value is in bounds set by the ParameterDefinition.
Parameters
val Value to set the ContinuousParameter to.
Implements Parameter.
Definition at line 23 of file ContinuousParameter.cpp.
References Parameter::getMax(), Parameter::getMin(), and val.
Member Data Documentation
val
coordinate ContinuousParameter::val private
Value of the ContinuousParameter.
Definition at line 16 of file ContinuousParameter.h.
Referenced by ContinuousParameter(), getVal(), and setVal().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/parameters/ContinuousParameter.h
/home/runner/work/simopticon/simopticon/src/parameters/ContinuousParameter.cpp