Simopticon: ValueMap Class Reference
ValueMap Class Reference
controller
A container managing a map data structure that maps Parameter combinations to their respective found values.
#include "ValueMap.h"
Public Member Functions
ValueMap (unsigned int topEntries=10)
Creates a ValueMap.
functionValue query (const vector< shared_ptr< Parameter >> &params)
Returns the value saved at the given Parameter combination.
void insert (const vector< shared_ptr< Parameter >> &params, functionValue val)
Adds the given Parameter combination and value to tba.
bool isKnown (const vector< shared_ptr< Parameter >> &cords)
Checks if a value has been recorded at the given Parameter combination.
bool isTopValue (const vector< shared_ptr< Parameter >> &cords)
Checks if the given Parameter combination is to be found in topVals.
const map< vector< shared_ptr< Parameter > >, functionValue, CmpVectorSharedParameter > & getValues ()
Returns the whole values member.
functionValue getMedian ()
Returns the median of all values using lowerValues and upperValues.
size_t getSize () const
Returns the number of inserted values.
list< pair< vector< shared_ptr< Parameter > >, functionValue > > getTopVals ()
Returns the best topEntries entries that are saved in topVals.
Private Member Functions
void updateMap ()
Takes all values in tba, adds them to lowerValues or upperValues and inserts them into values.
void addValue (const pair< vector< shared_ptr< Parameter >>, functionValue > &val, set< functionValue *, CmpPtrFunctionvalue > &set)
Inserts a single value into values and into lowerValues or upperValues depending on set argument.
Private Attributes
mutex operationsLock
Threadlock to avoid damage to the data structure when concurrent threads access it.
set< functionValue *, CmpPtrFunctionvalue > upperValues
Greater half of the values in values.
set< functionValue *, CmpPtrFunctionvalue > lowerValues
Lesser half of the values in values.
const unsigned int topEntries
Number of entries to be printed as best values at the end of the optimization process.
set< pair< const vector< shared_ptr< Parameter > >, functionValue >, CmpPairVectorSharedParameterFunctionvalue > topVals
Set of pairs of the best Parameter combinations and their respective values.
map< vector< shared_ptr< Parameter > >, functionValue, CmpVectorSharedParameter > values
Actual map that contains Parameter combinations and their respective values.
list< pair< vector< shared_ptr< Parameter > >, functionValue > > tba
Entries that have been added since last updateMap.
Detailed Description
A container managing a map data structure that maps Parameter combinations to their respective found values.
The class manages concurrent access using the operationsLock. Running median calculation is supported by using sets upperValues and lowerValues. Values are inserted into the data structure at once when updateMap is called. Before that they are saved in tba to avoid unnecessary costly insertion operations.
Definition at line 26 of file ValueMap.h.
Constructor & Destructor Documentation
ValueMap()
ValueMap::ValueMap (unsigned int topEntries = 10) explicit
Creates a ValueMap.
Parameters
topEntries Value to be assigned to topEntries.
Definition at line 7 of file ValueMap.cpp.
References topEntries.
Member Function Documentation
addValue()
void ValueMap::addValue (const pair< vector< shared_ptr< Parameter >>, functionValue > & val, set< functionValue *, CmpPtrFunctionvalue > & set) private
Inserts a single value into values and into lowerValues or upperValues depending on set argument.
Parameters
val Parameter combination and respective value to be inserted.
set Set that value is inserted in. Either lowerValues or upperValues.
Definition at line 45 of file ValueMap.cpp.
References topEntries, topVals, and values.
Referenced by updateMap().
getMedian()
functionValue ValueMap::getMedian ()
Returns the median of all values using lowerValues and upperValues.
If no values have been added, 0 is returned. Triggers updateMap.
Returns
A value representing the median of all values.
Definition at line 92 of file ValueMap.cpp.
References getSize(), lowerValues, operationsLock, updateMap(), and upperValues.
getSize()
size_t ValueMap::getSize () const
Returns the number of inserted values.
Values in tba are included.
Returns
An integral representing the number of inserted values.
Definition at line 104 of file ValueMap.cpp.
References tba, and values.
Referenced by getMedian(), isKnown(), and StubController::updateStatus().
getTopVals()
list< pair< vector< shared_ptr< Parameter > >, functionValue > > ValueMap::getTopVals ()
Returns the best topEntries entries that are saved in topVals.
Triggers updateMap.
Returns
A list of the best topEntries Parameter combinations and their respective values.
Definition at line 108 of file ValueMap.cpp.
References topVals, and updateMap().
Referenced by Controller::removeOldResultfiles(), and StubController::updateStatus().
getValues()
const map< vector< shared_ptr< Parameter > >, functionValue, CmpVectorSharedParameter > & ValueMap::getValues ()
Returns the whole values member.
Triggers updateMap.
Returns
A map reference to values.
Definition at line 129 of file ValueMap.cpp.
References updateMap(), and values.
insert()
void ValueMap::insert (const vector< shared_ptr< Parameter >> & params, functionValue val)
Adds the given Parameter combination and value to tba.
Parameters
params Parameter combination to be added.
val Value to be added.
Definition at line 77 of file ValueMap.cpp.
References tba.
isKnown()
bool ValueMap::isKnown (const vector< shared_ptr< Parameter >> & cords)
Checks if a value has been recorded at the given Parameter combination.
Triggers updateMap.
Parameters
cords Parameter combination that is checked.
Returns
A boolean value that represents if the value is known.
Definition at line 81 of file ValueMap.cpp.
References getSize(), operationsLock, updateMap(), and values.
isTopValue()
bool ValueMap::isTopValue (const vector< shared_ptr< Parameter >> & cords)
Checks if the given Parameter combination is to be found in topVals.
Triggers updateMap.
Parameters
cords Parameter combination that is checked.
Returns
A boolean value that represents if the value is one of the best topEntries entries in values.
Definition at line 113 of file ValueMap.cpp.
References Parameter::getVal(), topVals, and updateMap().
query()
functionValue ValueMap::query (const vector< shared_ptr< Parameter >> & params)
Returns the value saved at the given Parameter combination.
If no value is present, an exception is thrown. Triggers updateMap.
Parameters
params Parameter combination to which the value is requested.
Returns
The value saved in values at the given Parameter combination.
Definition at line 66 of file ValueMap.cpp.
References operationsLock, updateMap(), and values.
updateMap()
void ValueMap::updateMap () private
Takes all values in tba, adds them to lowerValues or upperValues and inserts them into values.
lowerValues and upperValues are sorted as is required by their constraints. Afterwards tba is cleared.
Definition at line 10 of file ValueMap.cpp.
References addValue(), lowerValues, operationsLock, tba, and upperValues.
Referenced by getMedian(), getTopVals(), getValues(), isKnown(), isTopValue(), and query().
Member Data Documentation
lowerValues
set<functionValue *, CmpPtrFunctionvalue> ValueMap::lowerValues private
Lesser half of the values in values.
Same size as or one element less than upperValues.
Definition at line 40 of file ValueMap.h.
Referenced by getMedian(), and updateMap().
operationsLock
mutex ValueMap::operationsLock private
Threadlock to avoid damage to the data structure when concurrent threads access it.
Definition at line 31 of file ValueMap.h.
Referenced by getMedian(), isKnown(), query(), and updateMap().
tba
list<pair<vector<shared_ptr<Parameter> >, functionValue> > ValueMap::tba private
Entries that have been added since last updateMap.
Will be inserted into values, upperValues and lowerValues when updateMap is called.
Definition at line 62 of file ValueMap.h.
Referenced by getSize(), insert(), and updateMap().
topEntries
const unsigned int ValueMap::topEntries private
Number of entries to be printed as best values at the end of the optimization process.
Can be configured in main config.
Definition at line 46 of file ValueMap.h.
Referenced by ValueMap(), and addValue().
topVals
set<pair<const vector<shared_ptr<Parameter> >, functionValue>, CmpPairVectorSharedParameterFunctionvalue> ValueMap::topVals private
Set of pairs of the best Parameter combinations and their respective values.
Contains not more than topEntries entries.
Definition at line 51 of file ValueMap.h.
Referenced by addValue(), getTopVals(), and isTopValue().
upperValues
set<functionValue *, CmpPtrFunctionvalue> ValueMap::upperValues private
Greater half of the values in values.
Same size as or one element more than lowerValues.
Definition at line 36 of file ValueMap.h.
Referenced by getMedian(), and updateMap().
values
map<vector<shared_ptr<Parameter> >, functionValue, CmpVectorSharedParameter> ValueMap::values private
Actual map that contains Parameter combinations and their respective values.
Definition at line 56 of file ValueMap.h.
Referenced by addValue(), getSize(), getValues(), isKnown(), and query().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/controller/ValueMap.h
/home/runner/work/simopticon/simopticon/src/controller/ValueMap.cpp