Simopticon: Levels Class Reference
Levels Class Reference
optimizer » direct
A providing functionality for the usage of different weightings between local and global search throughout the optimization using different levels.
#include "Levels.h"
Public Member Functions
unsigned char nextLevel ()
Switches currentLevel to the next local level if global is false.
list< shared_ptr< HyRect > > getRectSubset (const map< depth, set< shared_ptr< HyRect >, CmpSharedHyrect >, greater<>> &rects, size_t size) const
Calculates the subset of all given rectangles based on the current level and returns a list containing only the best HyRect per diagonal length.
double getEpsilon () const
Returns the epsilon value on the current level the DIRECT algorithm resides on.
unsigned char getLevel () const
Returns a number corresponding to the current level the optimization resides on.
bool isGlobal () const
Returns the value of global.
void setGlobal (bool val)
Sets the value of global.
Static Public Attributes
constexpr static const double L3_EPSILON = 1e-5
Epsilon value to be used when DIRECT algorithm uses level 3.
constexpr static const double L2_EPSILON = 1e-5
Epsilon value to be used when DIRECT algorithm uses level 2.
constexpr static const double L1_EPSILON = 1e-7
Epsilon value to be used when DIRECT algorithm uses level 1.
constexpr static const double L0_EPSILON = 0
Epsilon value to be used when DIRECT algorithm uses level 0.
constexpr static const long double L3_SIZE = 0.5
Fraction of rectangles in partition to be used on level 3 (only larger rectangles are considered).
constexpr static const long double L2_SIZE = 1
Fraction of rectangles in partition to be used on level 2 (only smaller rectangles are considered).
constexpr static const long double L1_SIZE = 0.95
Fraction of rectangles in partition to be used on level 1 (only smaller rectangles are considered).
constexpr static const long double L0_SIZE = 0.04
Fraction of rectangles in partition to be used on level 0 (only smaller rectangles are considered).
Private Attributes
level currentLevel = l2_0
Local level the optimization is currently using when global is false.
bool global = false
Defines whether global optimization (level 3) or one of the local levels (0-2) is used.
Detailed Description
A providing functionality for the usage of different weightings between local and global search throughout the optimization using different levels.
Definition at line 31 of file Levels.h.
Member Function Documentation
getEpsilon()
double Levels::getEpsilon () const
Returns the epsilon value on the current level the DIRECT algorithm resides on.
Either L3_EPSILON, L2_EPSILON, L1_EPSILON or L0_EPSILON.
Returns
A floating point value used as epsilon parameter on the current level.
Definition at line 57 of file Levels.cpp.
References getLevel(), L0_EPSILON, L1_EPSILON, L2_EPSILON, and L3_EPSILON.
getLevel()
unsigned char Levels::getLevel () const
Returns a number corresponding to the current level the optimization resides on.
Returns
An integral corresponding to the current level.
Definition at line 70 of file Levels.cpp.
References currentLevel, and global.
Referenced by getEpsilon(), getRectSubset(), DirectOptimizer::getStatus(), and nextLevel().
getRectSubset()
list< shared_ptr< HyRect > > Levels::getRectSubset (const map< depth, set< shared_ptr< HyRect >, CmpSharedHyrect >, greater<>> & rects, size_t size) const
Calculates the subset of all given rectangles based on the current level and returns a list containing only the best HyRect per diagonal length.
Parameters
rects Map containing all HyRect of the current partition grouped by HyRect::t and sorted by HyRect::avgValue.
size Number of HyRect in the given partition.
Returns
A list containing only the best HyRect per diagonal length in the subset based on the current level.
Definition at line 20 of file Levels.cpp.
References getLevel(), global, L0_SIZE, L1_SIZE, L2_SIZE, and L3_SIZE.
isGlobal()
bool Levels::isGlobal () const
Returns the value of global.
Returns
A boolean defining whether the optimization is currently in the global phase.
Definition at line 86 of file Levels.cpp.
References global.
Referenced by DirectOptimizer::runOptimization().
nextLevel()
unsigned char Levels::nextLevel ()
Switches currentLevel to the next local level if global is false.
Returns
A number representing the current level after switching.
Definition at line 12 of file Levels.cpp.
References currentLevel, getLevel(), and global.
Referenced by DirectOptimizer::runOptimization().
setGlobal()
void Levels::setGlobal (bool val)
Sets the value of global.
Parameters
val Defines whether global optimization should be used in the following iterations.
Definition at line 90 of file Levels.cpp.
References global.
Referenced by DirectOptimizer::runOptimization().
Member Data Documentation
currentLevel
level Levels::currentLevel = l2_0 private
Local level the optimization is currently using when global is false.
Definition at line 36 of file Levels.h.
Referenced by getLevel(), and nextLevel().
global
bool Levels::global = false private
Defines whether global optimization (level 3) or one of the local levels (0-2) is used.
Definition at line 40 of file Levels.h.
Referenced by getLevel(), getRectSubset(), isGlobal(), nextLevel(), and setGlobal().
L0_EPSILON
constexpr static const double Levels::L0_EPSILON = 0 static constexpr
Epsilon value to be used when DIRECT algorithm uses level 0.
Definition at line 58 of file Levels.h.
Referenced by getEpsilon().
L0_SIZE
constexpr static const long double Levels::L0_SIZE = 0.04 static constexpr
Fraction of rectangles in partition to be used on level 0 (only smaller rectangles are considered).
Definition at line 75 of file Levels.h.
Referenced by getRectSubset().
L1_EPSILON
constexpr static const double Levels::L1_EPSILON = 1e-7 static constexpr
Epsilon value to be used when DIRECT algorithm uses level 1.
Definition at line 54 of file Levels.h.
Referenced by getEpsilon().
L1_SIZE
constexpr static const long double Levels::L1_SIZE = 0.95 static constexpr
Fraction of rectangles in partition to be used on level 1 (only smaller rectangles are considered).
Definition at line 71 of file Levels.h.
Referenced by getRectSubset().
L2_EPSILON
constexpr static const double Levels::L2_EPSILON = 1e-5 static constexpr
Epsilon value to be used when DIRECT algorithm uses level 2.
Definition at line 50 of file Levels.h.
Referenced by getEpsilon().
L2_SIZE
constexpr static const long double Levels::L2_SIZE = 1 static constexpr
Fraction of rectangles in partition to be used on level 2 (only smaller rectangles are considered).
Definition at line 67 of file Levels.h.
Referenced by getRectSubset().
L3_EPSILON
constexpr static const double Levels::L3_EPSILON = 1e-5 static constexpr
Epsilon value to be used when DIRECT algorithm uses level 3.
Definition at line 46 of file Levels.h.
Referenced by getEpsilon(), and DirectOptimizer::runOptimization().
L3_SIZE
constexpr static const long double Levels::L3_SIZE = 0.5 static constexpr
Fraction of rectangles in partition to be used on level 3 (only larger rectangles are considered).
Definition at line 63 of file Levels.h.
Referenced by getRectSubset().
The documentation for this class was generated from the following files:
/home/runner/work/simopticon/simopticon/src/optimizer/direct/Levels.h
/home/runner/work/simopticon/simopticon/src/optimizer/direct/Levels.cpp