Simopticon: MonteCarlo Class Reference
MonteCarlo Class Reference
optimizer » montecarlo
A class capable of finding the minimum of a blackbox function using the Monte Carlo algorithm.
#include "MonteCarlo.h"
Public Member Functions
MonteCarlo (Controller &ctrl, const std::list< std::shared_ptr< ParameterDefinition >> &params, nlohmann::json config)
Creates a DirectOptimizer that evaluates functions with the given Controller, optimizes the given ParameterDefinition list and stops as defined by the given StoppingCondition.
void runOptimization () override
Starts the optimization using the Monte Carlo algorithm.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Optimizer
Optimizer (Controller &ctrl, std::list< std::shared_ptr< ParameterDefinition >> params)
Creates an Optimizer which can request values from the given Controller and tries to optimize the given parameters.
ValueMap & getValueMap () const
Returns a reference to Controller::valueMap.
std::string getName () override
Returns a string representing the name of the implementing component in natural language.
std::string getStatus () override
Returns a string representing the current state of the implementing component.
std::string getStatusBar () override
Returns a string representing the current progress of the calculations of the implementing component.
Public Member Functions inherited from Abortable
virtual void abort ()
Sets aborted to true.
Private Member Functions
void saveProgress (functionValue bestVal, size_t evaluations) const
Prints the current number of iterations, evaluations, rectangles and the current optimal value to a .csv file.
Private Attributes
size_t iterations = 1
Number of iterations completed.
const size_t parallelTrials
Number of (typically parallel executed) parameter combinations per iteration.
StoppingCondition stopCon
An object deciding when the optimization stops.
bool trackProgress
Defines if the current number of iterations, evaluations, rectangles and the optimal value should be recorded into a .csv file after each iteration.
std::string lastEvaluations
A string for logging purposes containing the evaluation of the simulation runs of the last iteration.
Additional Inherited Members
Protected Member Functions inherited from Optimizer
std::map< parameterCombination, functionValue > requestValues (const std::list< parameterCombination > &params)
Requests the values when using certain parameterCombinations from controller.
Protected Attributes inherited from Optimizer
std::list< std::shared_ptr< ParameterDefinition > > parameters
List of parameters to be optimized.
Protected Attributes inherited from Abortable
bool aborted = false
Defines if the process has been aborted, i.e.
Static Protected Attributes inherited from Status
static const std::string NO_STATUS_SUPPORT = "Component doesn't support status updates!"
Default message returned by getStatus and getStatusBar if the implementing class does not override the respective function.
static const std::string NO_NAME = "No name specified"
Default message returned by getName if the implementing class does not override the function.
Detailed Description
A class capable of finding the minimum of a blackbox function using the Monte Carlo algorithm.
Author
Burkhard Hensel
Definition at line 35 of file MonteCarlo.h.
Constructor & Destructor Documentation
MonteCarlo()
MonteCarlo::MonteCarlo (Controller & ctrl, const std::list< std::shared_ptr< ParameterDefinition >> & params, nlohmann::json config)
Creates a DirectOptimizer that evaluates functions with the given Controller, optimizes the given ParameterDefinition list and stops as defined by the given StoppingCondition.
Parameters
ctrl Controller to be used for evaluating the optimized function.
params ParameterDefinition list to be optimized.
config Configuration parameters as JSON.
Definition at line 15 of file MonteCarlo.cpp.
References MonteCarlo().
Referenced by MonteCarlo().
Member Function Documentation
getName()
std::string MonteCarlo::getName () override virtual
Returns a string representing the name of the implementing component in natural language.
Returns
A string containing the name of the component.
Reimplemented from Status.
Definition at line 83 of file MonteCarlo.cpp.
getStatus()
std::string MonteCarlo::getStatus () override virtual
Returns a string representing the current state of the implementing component.
May contain values of class members or other meaningful information. The returned string is always visible in StatusBar.
Returns
A string containing the state of the component.
Reimplemented from Status.
Definition at line 87 of file MonteCarlo.cpp.
References iterations, and lastEvaluations.
getStatusBar()
std::string MonteCarlo::getStatusBar () override virtual
Returns a string representing the current progress of the calculations of the implementing component.
The returned string is visible in StatusBar, when the component is actively calculating something. Must not exceed one console line!
Returns
A string containing the progress of a calculation.
Reimplemented from Status.
Definition at line 102 of file MonteCarlo.cpp.
runOptimization()
void MonteCarlo::runOptimization () override virtual
Starts the optimization using the Monte Carlo algorithm.
Only returns when an iteration has completed and stopCon deems the optimization complete or when abort was called in the last iteration.
Implements Optimizer.
Definition at line 22 of file MonteCarlo.cpp.
References Optimizer::getValueMap(), iterations, lastEvaluations, parallelTrials, saveProgress(), and trackProgress.
saveProgress()
void MonteCarlo::saveProgress (functionValue bestVal, size_t evaluations) const private
Prints the current number of iterations, evaluations, rectangles and the current optimal value to a .csv file.
Parameters
bestVal Value at the current minimum.
evaluations Number of evaluations conducted by the optimization.
Definition at line 71 of file MonteCarlo.cpp.
Referenced by runOptimization().
Member Data Documentation
iterations
size_t MonteCarlo::iterations = 1 private
Number of iterations completed.
Definition at line 40 of file MonteCarlo.h.
Referenced by getStatus(), and runOptimization().
lastEvaluations
std::string MonteCarlo::lastEvaluations private
A string for logging purposes containing the evaluation of the simulation runs of the last iteration.
Definition at line 57 of file MonteCarlo.h.
Referenced by getStatus(), and runOptimization().
parallelTrials
const size_t MonteCarlo::parallelTrials private
Number of (typically parallel executed) parameter combinations per iteration.
Definition at line 44 of file MonteCarlo.h.
Referenced by runOptimization().
stopCon
StoppingCondition MonteCarlo::stopCon private
An object deciding when the optimization stops.
Definition at line 48 of file MonteCarlo.h.
trackProgress
bool MonteCarlo::trackProgress private
Defines if the current number of iterations, evaluations, rectangles and the optimal value should be recorded into a .csv file after each iteration.
Can be set in config.
Definition at line 53 of file MonteCarlo.h.
Referenced by runOptimization().
The documentation for this class was generated from the following files:
/home/runner/work/Simopticon/Simopticon/src/optimizer/montecarlo/MonteCarlo.h
/home/runner/work/Simopticon/Simopticon/src/optimizer/montecarlo/MonteCarlo.cpp